# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9zjz6AGpKScwIXG_ngGuoyQz1NVYbNO

[1] Import librerie
"""

import csv
import json
import math
import os
import sys
import textwrap
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.ticker import MultipleLocator
from scipy import stats
from scipy.stats import entropy as scipy_entropy

try:
    from google.colab import files  # type: ignore
    IN_COLAB = True
except ImportError:
    files = None
    IN_COLAB = False

# In locale: ogni plt.show() salva un PNG; a fine script genero una galleria
# HTML con sidebar (click / frecce su-giu') e la apro nel browser.
if not IN_COLAB:
    import atexit
    import webbrowser
    import matplotlib
    matplotlib.use("Agg")

    _OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "grafici_output")
    os.makedirs(_OUT_DIR, exist_ok=True)
    for _f in os.listdir(_OUT_DIR):
        if _f.endswith((".png", ".html")):
            try:
                os.remove(os.path.join(_OUT_DIR, _f))
            except OSError:
                pass

    _figures_meta = []  # [(filename, titolo, gruppo)]

    def _estrai_titolo(fig):
        for ax in fig.get_axes():
            t = ax.get_title()
            if t:
                return t
        # fallback per le matrici di confusione (titolo messo via ax.text)
        for ax in fig.get_axes():
            for txt in ax.texts:
                s = txt.get_text()
                if any(k in s for k in ("Originale", "Varianti", "Maggioranza")):
                    return s
        return ""

    def _show_and_save(*args, **kwargs):
        n = len(_figures_meta) + 1
        filename = f"figura_{n:02d}.png"
        path = os.path.join(_OUT_DIR, filename)
        plt.savefig(path, dpi=120, bbox_inches="tight")
        titolo = _estrai_titolo(plt.gcf()) or f"Figura {n}"
        _figures_meta.append((filename, titolo, globals().get("GRUPPO", "Grafici")))
        print(f"  [{n:02d}] {titolo}")
        plt.close("all")

    plt.show = _show_and_save

    # Galleria a confronto: 1/2/4 pannelli affiancati, sidebar con le figure
    # raggruppate per tema, badge colorati = in quale pannello sta ogni figura.
    _TEMPLATE_GALLERIA = """<!doctype html>
<html lang="it"><head><meta charset="utf-8">
<title>Grafici Benchmark</title>
<style>
  *{box-sizing:border-box}
  body{margin:0;font-family:-apple-system,Segoe UI,sans-serif;display:flex;height:100vh;background:#eceff1}
  aside{width:330px;border-right:1px solid #ddd;overflow-y:auto;background:#fafafa;flex-shrink:0}
  aside h1{font-size:13px;margin:0;padding:12px 14px;border-bottom:1px solid #ddd;background:#fff}
  .layouts{display:flex;gap:6px;padding:10px 14px;border-bottom:1px solid #ddd;background:#fff;align-items:center}
  .layouts span{font-size:11px;color:#888;margin-right:4px}
  .layouts button{width:34px;height:26px;border:1px solid #bbb;background:#fff;border-radius:4px;cursor:pointer;font-weight:bold}
  .layouts button.sel{background:#2196F3;border-color:#2196F3;color:#fff}
  details{border-bottom:1px solid #eee}
  summary{padding:8px 14px;font-size:12px;font-weight:bold;cursor:pointer;background:#f0f0f0;user-select:none}
  ul{list-style:none;margin:0;padding:0}
  .item{display:flex;align-items:flex-start;gap:6px;padding:7px 10px 7px 14px;cursor:pointer;border-bottom:1px solid #f2f2f2;font-size:12px;line-height:1.3}
  .item:hover{background:#e3f2fd}
  .item .num{color:#999;font-weight:bold}
  .item .tit{flex:1}
  .item .badges{display:flex;gap:3px}
  .badge{width:16px;height:16px;border-radius:50%;color:#fff;font-size:10px;font-weight:bold;display:flex;align-items:center;justify-content:center}
  .b0{background:#2196F3}.b1{background:#FF9800}.b2{background:#4CAF50}.b3{background:#9C27B0}
  main{flex:1;display:grid;gap:8px;padding:8px;min-width:0}
  main[data-layout="1"]{grid-template-columns:1fr;grid-template-rows:1fr}
  main[data-layout="2"]{grid-template-columns:1fr 1fr;grid-template-rows:1fr}
  main[data-layout="4"]{grid-template-columns:1fr 1fr;grid-template-rows:1fr 1fr}
  .pannello{border:2px solid #cfd8dc;border-radius:6px;background:#fff;display:flex;flex-direction:column;overflow:hidden;cursor:pointer;min-height:0;min-width:0}
  .pannello.attivo{box-shadow:0 0 0 2px currentColor}
  .pannello .barra{display:flex;align-items:center;gap:8px;padding:6px 10px;border-bottom:1px solid #eee}
  .pannello .tag{font-size:10px;font-weight:bold;color:#fff;padding:2px 7px;border-radius:10px}
  .pannello h2{font-size:12px;margin:0;flex:1;font-weight:600;color:#37474F}
  .pannello img{flex:1;min-height:0;width:100%;object-fit:contain;background:#fff}
  .hint{position:fixed;bottom:6px;right:12px;font-size:11px;color:#78909c;background:#fff;padding:3px 8px;border-radius:4px;box-shadow:0 1px 3px rgba(0,0,0,.15)}
</style></head><body>
<aside>
  <h1>Grafici (__N__) &mdash; __CSV__</h1>
  <div class="layouts"><span>Pannelli:</span>
    <button data-n="1">1</button><button data-n="2" class="sel">2</button><button data-n="4">4</button>
  </div>
  <div id="gruppi">__SEZIONI__</div>
</aside>
<main id="pannelli" data-layout="2"></main>
<div class="hint">clic pannello = attiva &middot; clic figura = assegna &middot; &uarr;&darr; figura &middot; &larr;&rarr; pannello &middot; 1/2/4 layout &middot; doppio clic = apri PNG</div>
<script>
const FIGURE = __DATA__;
const COLORI = ['#2196F3','#FF9800','#4CAF50','#9C27B0'];
let layout = 2, attivo = 0;
const assegnate = [0,1,2,3].map(i => Math.min(i, FIGURE.length-1));
const main = document.getElementById('pannelli');
const pannelli = [];
for (let i=0;i<4;i++){
  const p = document.createElement('section');
  p.className = 'pannello';
  p.style.color = COLORI[i];
  p.innerHTML = '<div class="barra"><span class="tag" style="background:'+COLORI[i]+'">'+(i+1)+
                '</span><h2></h2></div><img alt="">';
  p.addEventListener('click', ()=>{ attivo = i; render(); });
  p.addEventListener('dblclick', ()=>window.open(FIGURE[assegnate[i]].fn));
  main.appendChild(p); pannelli.push(p);
}
const items = [...document.querySelectorAll('.item')];
items.forEach(it => it.addEventListener('click', ()=>{ assegnate[attivo] = +it.dataset.i; render(); }));
function render(){
  main.dataset.layout = layout;
  if (attivo >= layout) attivo = 0;
  pannelli.forEach((p,i)=>{
    p.style.display = i < layout ? '' : 'none';
    p.classList.toggle('attivo', i === attivo);
    const f = FIGURE[assegnate[i]];
    p.querySelector('h2').textContent = f.titolo;
    p.querySelector('img').src = f.fn;
  });
  items.forEach(it=>{ it.querySelector('.badges').innerHTML = ''; });
  for (let i=0;i<layout;i++){
    const it = items[assegnate[i]];
    if (!it) continue;
    const b = document.createElement('span');
    b.className = 'badge b'+i; b.textContent = i+1;
    it.querySelector('.badges').appendChild(b);
  }
}
document.querySelectorAll('.layouts button').forEach(btn=>{
  btn.addEventListener('click', ()=>{
    layout = +btn.dataset.n;
    document.querySelectorAll('.layouts button').forEach(b=>b.classList.toggle('sel', b===btn));
    render();
  });
});
document.addEventListener('keydown', e=>{
  if (e.key === 'ArrowDown' || e.key === 'ArrowUp'){
    e.preventDefault();
    const d = e.key === 'ArrowDown' ? 1 : -1;
    assegnate[attivo] = (assegnate[attivo] + d + FIGURE.length) % FIGURE.length;
    render();
    const it = items[assegnate[attivo]];
    if (it) it.scrollIntoView({block:'nearest'});
  } else if (e.key === 'ArrowRight' || e.key === 'ArrowLeft'){
    const d = e.key === 'ArrowRight' ? 1 : -1;
    attivo = (attivo + d + layout) % layout;
    render();
  } else if (['1','2','4'].includes(e.key)){
    layout = +e.key;
    document.querySelectorAll('.layouts button').forEach(b=>b.classList.toggle('sel', b.dataset.n===e.key));
    render();
  }
});
render();
</script></body></html>"""

    def _genera_galleria():
        if not _figures_meta:
            return
        dati = json.dumps([{"fn": fn, "titolo": t} for fn, t, _g in _figures_meta],
                          ensure_ascii=False)
        gruppi = {}
        for i, (fn, t, g) in enumerate(_figures_meta):
            gruppi.setdefault(g, []).append((i, t))
        sezioni = []
        for g, voci in gruppi.items():
            righe = "\n".join(
                f'<li class="item" data-i="{i}"><span class="num">{i + 1:02d}</span>'
                f'<span class="tit">{t}</span><span class="badges"></span></li>'
                for i, t in voci)
            sezioni.append(f'<details open><summary>{g} ({len(voci)})</summary>'
                           f'<ul>{righe}</ul></details>')
        csv_nome = os.path.basename(str(globals().get("NOME_FILE", "")))
        html = (_TEMPLATE_GALLERIA
                .replace("__CSV__", csv_nome)
                .replace("__N__", str(len(_figures_meta)))
                .replace("__SEZIONI__", "\n".join(sezioni))
                .replace("__DATA__", dati))
        index_path = os.path.join(_OUT_DIR, "index.html")
        with open(index_path, "w", encoding="utf-8") as f:
            f.write(html)
        url = "file:///" + os.path.abspath(index_path).replace("\\", "/")
        print(f"\nGalleria pronta: {url}")
        webbrowser.open(url)

    atexit.register(_genera_galleria)

"""[2] Costanti di visualizzazione"""

NUM_TEST = 3000
RIPETIZIONI_PER_DOMANDA = 5

"""[3] Caricamento"""

if IN_COLAB:
    print("Seleziona il file CSV con i risultati del benchmark:")
    uploaded = files.upload()
    if uploaded:
        NOME_FILE = list(uploaded.keys())[0]
        print(f"\nFile '{NOME_FILE}' caricato con successo!")
    else:
        print("\nNessun file caricato. Assicurati di selezionare il file prima di procedere.")
        sys.exit(1)
else:
    # Esecuzione locale: prendi il path dal primo argomento CLI, altrimenti
    # cerca risultati_benchmark.csv nella root del progetto.
    if len(sys.argv) > 1:
        NOME_FILE = sys.argv[1]
    else:
        candidati = [
            os.path.join(os.path.dirname(__file__), "..", "risultati_benchmark.csv"),
            "risultati_benchmark.csv",
        ]
        NOME_FILE = next((p for p in candidati if os.path.exists(p)), None)
        if NOME_FILE is None:
            print("⚠️ Nessun CSV trovato. Passa il path come argomento: "
                  "python generatore_grafici.py path/al/file.csv")
            sys.exit(1)
    print(f"File '{NOME_FILE}' selezionato (esecuzione locale).")

"""[4] Analizzatore di benchmark: accuratezza ed entropia (DATASET-AGNOSTICO)

Lo script non sa quali siano le classi del dataset: le rileva dalle chiavi del
campo ``probabilita`` nel CSV (escludendo "altro"). Funziona quindi sia per BoolQ
(classi {true, false}) sia per il multiple-choice (classi {A, B, C, D, E}).

Una sola funzione di entropia, parametrizzata da ``includi_altro``:
  - senza "altro": entropia sulle SOLE classi valide       -> base = K
  - con   "altro": entropia su classi valide + "altro"     -> base = K + 1
Usando base = numero di classi l'entropia resta normalizzata in [0, 1].
Per BoolQ "senza altro" coincide con la vecchia entropia BINARIA e "con altro"
con quella TERNARIA; per il multiple-choice si ottiene l'entropia su K o K+1
classi a seconda che si includa o meno la massa "altro".
"""


def entropia(probs: dict, classi: list, includi_altro: bool = True) -> float:
    """Entropia di Shannon normalizzata in [0, 1] sulla distribuzione di risposta.

    ``classi`` sono le classi valide del dataset; con ``includi_altro`` si
    aggiunge il bucket "altro". La base del log e' il numero di chiavi, cosi'
    il massimo (distribuzione uniforme) vale esattamente 1.0.
    """
    chiavi = list(classi) + (["altro"] if includi_altro else [])
    if len(chiavi) < 2:
        return 0.0
    valori = [probs.get(k, 0.0) for k in chiavi]
    somma = sum(valori)
    if somma <= 0:
        return 0.0
    p = [v / somma for v in valori]
    return scipy_entropy(p, base=len(chiavi))


def kl_simmetrica(p: dict, q: dict, classi: list, includi_altro: bool = True) -> float:
    """Divergenza di Kullback-Leibler simmetrizzata: [D(P||Q) + D(Q||P)] / 2.

    Stesse convenzioni di ``entropia``: distribuzioni rinormalizzate sulle
    chiavi considerate e log in base ``len(chiavi)``, cosi' la scala e'
    confrontabile con l'entropia normalizzata. I termini con P(x) = 0 o
    Q(x) = 0 contano zero.
    """
    chiavi = list(classi) + (["altro"] if includi_altro else [])
    if len(chiavi) < 2:
        return 0.0

    def _normalizza(d):
        v = [d.get(k, 0.0) for k in chiavi]
        s = sum(v)
        return [x / s for x in v] if s > 0 else None

    P = _normalizza(p)
    Q = _normalizza(q)
    if P is None or Q is None:
        return 0.0
    base = len(chiavi)

    def _dkl(a, b):
        return sum(x * math.log(x / y, base) for x, y in zip(a, b) if x > 0 and y > 0)

    return (_dkl(P, Q) + _dkl(Q, P)) / 2


def distribuzione_media(alternative: list, classi: list, includi_altro: bool) -> dict:
    """Distribuzione media (ensemble) sulle ripetizioni, rinormalizzata per riga.

    Ogni ripetizione viene prima rinormalizzata sulle chiavi considerate, poi si
    fa la media aritmetica delle distribuzioni valide (somma > 0).
    """
    chiavi = list(classi) + (["altro"] if includi_altro else [])
    acc = {k: 0.0 for k in chiavi}
    k_valide = 0
    for alt in alternative:
        prob = alt.get("probabilita", {})
        somma = sum(prob.get(k, 0.0) for k in chiavi)
        if somma > 0:
            for k in chiavi:
                acc[k] += prob.get(k, 0.0) / somma
            k_valide += 1
    if k_valide == 0:
        return {k: 0.0 for k in chiavi}
    return {k: acc[k] / k_valide for k in chiavi}


class RisultatiBenchmark:
    def __init__(self):
        # Classi valide del dataset (chiavi di "probabilita", senza "altro")
        self.classi = []
        self.risultati_per_tabella = []
        # Accuratezza ai tre livelli (conteggi corrette/totali): vale per ogni N
        self.corrette_orig = 0
        self.totali_orig = 0
        self.corrette_mod = 0
        self.totali_mod = 0
        self.corrette_magg = 0
        self.totali_magg = 0
        # Matrici di confusione 2x2 (popolate solo per dataset binari, es. BoolQ)
        self.tp = self.tn = self.fp = self.fn = 0
        self.tp_orig = self.tn_orig = self.fp_orig = self.fn_orig = 0
        self.tp_mod = self.tn_mod = self.fp_mod = self.fn_mod = 0


def carica_da_csv(filename) -> RisultatiBenchmark:
    risultati = RisultatiBenchmark()
    with open(filename, mode='r', encoding='utf-8') as file:
        reader = csv.DictReader(file)
        for row in reader:
            reale = row["reale"].strip()
            alternative = json.loads(row["alternative_json"])
            if not alternative:
                continue

            # Rileva le classi del dataset dalla prima riga utile (chiavi di
            # "probabilita" escluso "altro"). Mantiene l'ordine del motore.
            if not risultati.classi:
                chiavi = list(alternative[0].get("probabilita", {}).keys())
                risultati.classi = [c for c in chiavi if c != "altro"]
            classi = risultati.classi
            binario = (len(classi) == 2)

            # Maggioranza = argmax della SOMMA delle probabilita' per classe
            # valida su tutte le ripetizioni (ensemble grezzo).
            somma_cls = {c: 0.0 for c in classi}
            for a in alternative:
                prob = a.get("probabilita", {})
                for c in classi:
                    somma_cls[c] += prob.get(c, 0.0)
            risposta_maggioranza = max(somma_cls, key=somma_cls.get) if somma_cls else "altro"
            esito_corretto = (risposta_maggioranza == reale)

            # Originale (indice 0)
            risp_orig = alternative[0]["risposta_pulita"].strip()
            risultati.totali_orig += 1
            if risp_orig == reale:
                risultati.corrette_orig += 1

            # Varianti (indici 1..)
            for alt in alternative[1:]:
                risultati.totali_mod += 1
                if alt["risposta_pulita"].strip() == reale:
                    risultati.corrette_mod += 1

            # Maggioranza
            risultati.totali_magg += 1
            if esito_corretto:
                risultati.corrette_magg += 1

            # Matrici 2x2: hanno senso solo per dataset binari (true/false).
            if binario:
                if risp_orig == "true" and reale == "true":     risultati.tp_orig += 1
                elif risp_orig == "false" and reale == "false": risultati.tn_orig += 1
                elif risp_orig == "true" and reale == "false":  risultati.fp_orig += 1
                elif risp_orig == "false" and reale == "true":  risultati.fn_orig += 1
                for alt in alternative[1:]:
                    rm = alt["risposta_pulita"].strip()
                    if rm == "true" and reale == "true":     risultati.tp_mod += 1
                    elif rm == "false" and reale == "false": risultati.tn_mod += 1
                    elif rm == "true" and reale == "false":  risultati.fp_mod += 1
                    elif rm == "false" and reale == "true":  risultati.fn_mod += 1
                if esito_corretto:
                    if reale == "true": risultati.tp += 1
                    else: risultati.tn += 1
                else:
                    if reale == "false": risultati.fp += 1
                    else: risultati.fn += 1

            risultati.risultati_per_tabella.append({
                "id": int(row["id"]),
                "domanda": row["domanda"],
                "reale": reale,
                "alternative": alternative,
                "corretta": esito_corretto,
                "risposta_maggioranza": risposta_maggioranza,
            })
    return risultati


"""[5] Funzioni di plotting (fattorizzate, riusate da tutti i blocchi)"""


def stampa_matrice(tp, tn, fp, fn, titolo):
    """Matrice di confusione 2x2 disegnata a mano (solo dataset binari)."""
    fig, ax = plt.subplots(figsize=(4, 3.2))
    ax.set_xlim(0, 3)
    ax.set_ylim(0, 3)
    ax.axis('off')

    ax.text(1.5, 2.85, titolo, ha='center', va='center',
            fontsize=12, fontweight='bold')

    ax.text(1.5, 2.55, "Modello: T", ha='center', va='center', fontsize=10)
    ax.text(2.5, 2.55, "Modello: F", ha='center', va='center', fontsize=10)

    ax.text(0.5, 1.75, "Realtà: T", ha='center', va='center', fontsize=10)
    ax.text(0.5, 0.75, "Realtà: F", ha='center', va='center', fontsize=10)

    verde = "#c6efce"
    rosso = "#ffc7ce"
    verde_testo = "#006100"
    rosso_testo = "#9c0006"

    celle = [
        (1.0, 1.25, verde, verde_testo, "TP", tp),
        (2.0, 1.25, rosso, rosso_testo, "FN", fn),
        (1.0, 0.25, rosso, rosso_testo, "FP", fp),
        (2.0, 0.25, verde, verde_testo, "TN", tn),
    ]

    for (x, y, bg, fg, label, val) in celle:
        rect = mpatches.FancyBboxPatch(
            (x, y), 0.9, 0.9,
            boxstyle="square,pad=0.02",
            linewidth=1, edgecolor='gray',
            facecolor=bg
        )
        ax.add_patch(rect)
        ax.text(x + 0.45, y + 0.62, label,
                ha='center', va='center',
                fontsize=11, fontweight='bold', color=fg)
        ax.text(x + 0.45, y + 0.28, str(val),
                ha='center', va='center',
                fontsize=13, fontweight='bold', color=fg)

    plt.tight_layout()
    plt.show()


def stampa_metriche(tp, tn, fp, fn, nome):
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall    = tp / (tp + fn) if (tp + fn) > 0 else 0
    accuracy  = (tp + tn) / (tp + tn + fp + fn) if (tp + tn + fp + fn) > 0 else 0

    print(f"--- {nome} ---")
    print(f"Accuracy : {accuracy:.4f}")
    # Quando il modello dice TRUE, quante volte ha ragione?
    print(f"Precision: {precision:.4f}")
    # Di tutti i TRUE reali, quanti ne ha trovati il modello?
    print(f"Recall   : {recall:.4f}")
    print()


def conta_confusione(righe, classi, livello):
    """Matrice K x (K+1): riga = classe reale, colonna = predetta (+ 'altro').

    ``livello`` in {originale, varianti, maggioranza}; l'ultima colonna raccoglie
    le risposte che non sono una classe valida (vuote, testo non parsato, ...).
    """
    idx = {c: i for i, c in enumerate(classi)}
    M = np.zeros((len(classi), len(classi) + 1), dtype=int)
    for riga in righe:
        r = idx.get(riga["reale"])
        if r is None:
            continue
        if livello == "originale":
            predette = [riga["alternative"][0]["risposta_pulita"].strip()]
        elif livello == "varianti":
            predette = [a["risposta_pulita"].strip() for a in riga["alternative"][1:]]
        else:  # maggioranza
            predette = [riga["risposta_maggioranza"]]
        for p in predette:
            M[r, idx.get(p, len(classi))] += 1
    return M


def stampa_matrice_kxk(M, classi, titolo):
    """Heatmap della matrice di confusione K x (K+1) per dataset multi-classe.

    La diagonale (bordo verde) sono le risposte corrette. I marginali di colonna
    ("quante volte il modello ha risposto A/B/...") leggono il bias di posizione:
    se la classe giusta e' distribuita ~uniformemente, colonne sbilanciate
    indicano preferenza per certe lettere.
    """
    etichette_col = list(classi) + ["altro"]
    fig, ax = plt.subplots(figsize=(7.5, 6), dpi=100)
    im = ax.imshow(M, cmap='Blues')
    ax.set_title(titolo, pad=15)
    ax.set_xticks(range(len(etichette_col)))
    ax.set_xticklabels([f"Modello: {c}" for c in etichette_col], rotation=30, ha='right')
    ax.set_yticks(range(len(classi)))
    ax.set_yticklabels([f"Reale: {c}" for c in classi])
    soglia = M.max() / 2 if M.max() > 0 else 0
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            ax.text(j, i, str(M[i, j]), ha='center', va='center',
                    fontweight='bold',
                    color='white' if M[i, j] > soglia else '#37474F')
        ax.add_patch(mpatches.Rectangle((i - 0.5, i - 0.5), 1, 1, fill=False,
                                        edgecolor='#4CAF50', linewidth=2.5))
    fig.colorbar(im, ax=ax, shrink=0.8)
    plt.tight_layout()

    totale = M.sum()
    if totale > 0:
        marginali = M.sum(axis=0) / totale * 100
        print(f"  {titolo} — risposte del modello per classe (bias di posizione):")
        print("    " + "  ".join(f"{c}: {m:.1f}%" for c, m in zip(etichette_col, marginali)))
    plt.show()


def _nuvola_punti(ax, centro, valori, nome_cmap):
    """Nuvola di punti leggibile anche con migliaia di valori sovrapposti.

    Tre accorgimenti combinati:
      - colore sfumato con la densita' locale (istogramma sui valori):
        chiaro = zona rada, scuro = zona affollata;
      - jitter orizzontale proporzionale alla densita' (stile sina plot):
        le fasce affollate si allargano, i punti isolati restano stretti;
      - alpha e dimensione adattivi al numero di punti.
    """
    v = np.asarray(valori, dtype=float)
    n = len(v)
    if n == 0:
        return
    nbins = int(np.clip(np.sqrt(n), 10, 60))
    conti, bordi = np.histogram(v, bins=nbins)
    idx = np.clip(np.digitize(v, bordi[1:-1]), 0, nbins - 1)
    dens = np.log1p(conti[idx].astype(float))  # scala log: sfumatura leggibile
    dens /= dens.max() if dens.max() > 0 else 1.0  # anche fuori dal picco a 0
    jitter = np.random.uniform(-1, 1, n) * (0.03 + 0.17 * dens)
    alpha = float(np.clip(2000.0 / n, 0.08, 0.7))
    size = float(np.clip(8000.0 / n, 4.0, 36.0))
    colori = plt.get_cmap(nome_cmap)(0.35 + 0.60 * dens)
    ordine = np.argsort(dens)  # i punti densi sopra, il nucleo resta visibile
    ax.scatter(centro + jitter[ordine], v[ordine], s=size,
               c=colori[ordine], alpha=alpha, linewidths=0, zorder=2)


def _scatter_box(ax, corrette, errate):
    """Boxplot + nuvola densita'-aware di due gruppi (corrette / errate)."""
    bp = ax.boxplot([corrette, errate], positions=[1, 2], widths=0.4,
                    patch_artist=True, showfliers=False, zorder=3)
    for patch, edge in zip(bp['boxes'], ['#4CAF50', '#F44336']):
        patch.set_facecolor('none')
        patch.set_edgecolor(edge)
        patch.set_linewidth(1.5)
    for median in bp['medians']:
        median.set(color='black', linewidth=2)

    _nuvola_punti(ax, 1, corrette, 'Greens')
    _nuvola_punti(ax, 2, errate, 'Reds')

    ax.set_xticks([1, 2])
    ax.set_xticklabels(['Risposte Esatte', 'Risposte Sbagliate'],
                       fontsize=11, fontweight='bold')
    ax.legend(handles=[
        mpatches.Patch(color='#4CAF50', label=f'Esatte ({len(corrette)})'),
        mpatches.Patch(color='#F44336', label=f'Sbagliate ({len(errate)})'),
    ], loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=2)
    ax.grid(axis='y', linestyle='--', alpha=0.7, zorder=0)


def plot_corrette_errate(valori, esiti, titolo, ylabel, ylim=(-0.05, 1.05)):
    """Boxplot+scatter di una metrica per gruppi corrette/errate, con Pearson."""
    corrette = [v for v, ok in zip(valori, esiti) if ok]
    errate = [v for v, ok in zip(valori, esiti) if not ok]
    fig, ax = plt.subplots(figsize=(8, 6), dpi=100)
    _scatter_box(ax, corrette, errate)
    ax.set_title(titolo, pad=15)
    ax.set_ylabel(ylabel)
    if ylim is not None:
        ax.set_ylim(*ylim)
    if len(valori) > 1:
        corr = [0 if ok else 1 for ok in esiti]
        pr = stats.pearsonr(valori, corr)
        print(f"  Pearson r = {pr.statistic:.4f} (p={pr.pvalue:.2e}) — {titolo}")
    plt.show()


def plot_accuratezza_quartili(valori, esiti, titolo, colore='#2196F3', edge='#1565C0'):
    """Accuratezza per quartili della metrica (Q1 = piu' sicuro ... Q4 = piu' indeciso)."""
    if not valori:
        return
    limiti = np.percentile(valori, [0, 25, 50, 75, 100])
    etichette = [f"Q{i+1}\n({limiti[i]:.4f} - {limiti[i+1]:.4f})" for i in range(4)]
    corrette = [0] * 4
    totali = [0] * 4
    for v, ok in zip(valori, esiti):
        idx = min(max(int(np.digitize(v, limiti)) - 1, 0), 3)
        totali[idx] += 1
        if ok:
            corrette[idx] += 1
    acc = [(c / t * 100) if t > 0 else 0.0 for c, t in zip(corrette, totali)]

    fig, ax = plt.subplots(figsize=(9, 5), dpi=100)
    barre = ax.bar(etichette, acc, color=colore, alpha=0.8, edgecolor=edge, linewidth=1.5)
    for bar, t in zip(barre, totali):
        h = bar.get_height()
        ax.annotate(f'{h:.2f}%\n(n={t})',
                    xy=(bar.get_x() + bar.get_width() / 2, h),
                    xytext=(0, 3), textcoords="offset points",
                    ha='center', va='bottom', fontweight='bold', fontsize=9)
    ax.set_title(titolo, pad=15)
    ax.set_xlabel("Quartili (Q1 = Più Sicuro  ⟶  Q4 = Più Indeciso)")
    ax.set_ylabel("Accuratezza (%)")
    ax.set_ylim(0, 115)
    ax.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()


def raccogli_entropia(res, livello, includi_altro):
    """(valori_entropia, esiti) per ``livello`` in {originale, maggioranza, tutte}.

    - originale: entropia della sola variante originale (indice 0);
    - tutte: entropia di ogni variante (originale + perturbate);
    - maggioranza: entropia della distribuzione media (ensemble) della domanda.
    L'esito (corretta/errata) e' coerente col livello.
    """
    classi = res.classi
    valori = []
    esiti = []
    for riga in res.risultati_per_tabella:
        if livello == "originale":
            alt = riga["alternative"][0]
            valori.append(entropia(alt.get("probabilita", {}), classi, includi_altro))
            esiti.append(alt["risposta_pulita"].strip() == riga["reale"])
        elif livello == "tutte":
            for alt in riga["alternative"]:
                valori.append(entropia(alt.get("probabilita", {}), classi, includi_altro))
                esiti.append(alt.get("risposta_pulita", "").strip() == riga["reale"])
        elif livello == "maggioranza":
            media = distribuzione_media(riga["alternative"], classi, includi_altro)
            valori.append(entropia(media, classi, includi_altro))
            esiti.append(riga["corretta"])
    return valori, esiti


def descrittori_per_domanda(res, includi_altro):
    """I 9 descrittori per domanda richiesti dal relatore, piu' gli esiti.

    Nomi secondo le convenzioni della letteratura (tra parentesi il nome
    "storico" usato finora): Hpmean = entropia della distribuzione media,
    Hmean = media delle entropie delle ripetizioni, Jensen = divergenza di
    Jensen-Shannon (= Hpmean - Hmean), KLmax = max KL simmetrica sulle coppie.

    Le righe con meno di 2 ripetizioni sono escluse (il max KL richiede almeno
    una coppia), cosi' tutti i descrittori restano allineati sulle stesse domande.
    """
    descr = {
        "[1] Hpmean (entropia della media)": [],
        "[2] Hmean (media delle entropie)": [],
        "[3] Hmax (massima entropia)": [],
        "[4] Hmin (minima entropia)": [],
        "[5] KLmax (max KL)": [],
        "[6] Jensen (entropia della media - media delle entropie)": [],
        "[7] Hmax - Hmin (massima - minima entropia)": [],
        "[8] Hmax - KLmax (massima entropia - max KL)": [],
        "[9] Hmin - KLmax (minima entropia - max KL)": [],
    }
    esiti = []
    for riga in res.risultati_per_tabella:
        alts = [a.get("probabilita", {}) for a in riga["alternative"]]
        if len(alts) < 2:
            continue
        ents = [entropia(p, res.classi, includi_altro) for p in alts]
        ent_media = entropia(
            distribuzione_media(riga["alternative"], res.classi, includi_altro),
            res.classi, includi_altro)
        media_ent = float(np.mean(ents))
        max_ent = max(ents)
        min_ent = min(ents)
        max_kl = max(kl_simmetrica(alts[i], alts[j], res.classi, includi_altro)
                     for i in range(len(alts)) for j in range(i + 1, len(alts)))
        descr["[1] Hpmean (entropia della media)"].append(ent_media)
        descr["[2] Hmean (media delle entropie)"].append(media_ent)
        descr["[3] Hmax (massima entropia)"].append(max_ent)
        descr["[4] Hmin (minima entropia)"].append(min_ent)
        descr["[5] KLmax (max KL)"].append(max_kl)
        descr["[6] Jensen (entropia della media - media delle entropie)"].append(ent_media - media_ent)
        descr["[7] Hmax - Hmin (massima - minima entropia)"].append(max_ent - min_ent)
        descr["[8] Hmax - KLmax (massima entropia - max KL)"].append(max_ent - max_kl)
        descr["[9] Hmin - KLmax (minima entropia - max KL)"].append(min_ent - max_kl)
        esiti.append(riga["corretta"])
    return descr, esiti


"""[6] Esecuzione: caricamento e rilevamento delle classi"""

res = carica_da_csv(NOME_FILE)

K = len(res.classi)
binario = (K == 2)
print(f"Classi rilevate: {res.classi} (K={K}) | dataset {'BINARIO' if binario else 'MULTI-CLASSE'}")

"""[7] Accuratezza globale (Originale / Varianti / Maggioranza)"""

GRUPPO = "Accuratezza"

acc_orig = res.corrette_orig / res.totali_orig * 100 if res.totali_orig else 0.0
acc_mod = res.corrette_mod / res.totali_mod * 100 if res.totali_mod else 0.0
acc_magg = res.corrette_magg / res.totali_magg * 100 if res.totali_magg else 0.0
print(f"ACCURATEZZA  Originali: {acc_orig:.2f}%  |  Varianti: {acc_mod:.2f}%  |  Maggioranza: {acc_magg:.2f}%")

fig, ax = plt.subplots(figsize=(7, 5), dpi=100)
nomi = ['Originale', 'Varianti', 'Maggioranza']
valori_acc = [acc_orig, acc_mod, acc_magg]
barre = ax.bar(nomi, valori_acc, color=['#2196F3', '#FF9800', '#4CAF50'],
               alpha=0.85, edgecolor='#37474F', linewidth=1.2)
for bar, v in zip(barre, valori_acc):
    ax.annotate(f'{v:.2f}%', xy=(bar.get_x() + bar.get_width() / 2, v),
                xytext=(0, 3), textcoords="offset points", ha='center',
                va='bottom', fontweight='bold', fontsize=11)
ax.set_title("Accuratezza globale (Originale / Varianti / Maggioranza)", pad=15)
ax.set_ylabel("Accuratezza (%)")
ax.set_ylim(0, 115)
ax.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""[8] Matrici di confusione 2x2 + precision/recall: SOLO dataset binari"""

GRUPPO = "Matrici di confusione"

if binario:
    stampa_matrice(res.tp_orig, res.tn_orig, res.fp_orig, res.fn_orig, f"Originale ({acc_orig:.1f}%)")
    stampa_matrice(res.tp_mod,  res.tn_mod,  res.fp_mod,  res.fn_mod,  f"Varianti ({acc_mod:.1f}%)")
    stampa_matrice(res.tp,      res.tn,      res.fp,      res.fn,      f"Maggioranza ({acc_magg:.1f}%)")
    stampa_metriche(res.tp_orig, res.tn_orig, res.fp_orig, res.fn_orig, "Originale")
    stampa_metriche(res.tp_mod,  res.tn_mod,  res.fp_mod,  res.fn_mod,  "Varianti")
    stampa_metriche(res.tp,      res.tn,      res.fp,      res.fn,      "Maggioranza")
else:
    for livello, nome, acc in (("originale", "Originale", acc_orig),
                               ("varianti", "Varianti", acc_mod),
                               ("maggioranza", "Maggioranza", acc_magg)):
        M = conta_confusione(res.risultati_per_tabella, res.classi, livello)
        stampa_matrice_kxk(M, res.classi,
                           f"Matrice {K}x{K} — {nome} ({acc:.1f}%)")
    print("Multi-classe: precision/recall per lettera non riportate "
          "(le lettere sono posizioni, non classi semantiche); la metrica di sintesi è l'accuracy.")

"""[9] Entropia vs accuratezza, per livello x (senza / con "altro")

Genera, per ogni combinazione, il boxplot+scatter corrette/errate e le barre di
accuratezza per quartili di entropia. Per BoolQ "senza altro"=binaria,
"con altro"=ternaria; per il multiple-choice = entropia su K o K+1 classi.
"""

LIVELLI = [
    ("originale", "Domanda Originale"),
    ("maggioranza", "Risposta di Maggioranza"),
    ("tutte", "Originale + Varianti"),
]

for includi_altro in (False, True):
    n_cls = K + (1 if includi_altro else 0)
    tag = f"{'con' if includi_altro else 'senza'} altro, {n_cls} classi"
    GRUPPO = f"Entropia ({tag})"
    colore, edge = ('#FF9800', '#E65100') if includi_altro else ('#2196F3', '#1565C0')
    for livello, etich in LIVELLI:
        valori, esiti = raccogli_entropia(res, livello, includi_altro)
        plot_corrette_errate(
            valori, esiti,
            f"Entropia ({tag}) — {etich} vs Accuratezza",
            f"Entropia normalizzata [0=Sicuro, 1=Indeciso] ({tag})")
        plot_accuratezza_quartili(
            valori, esiti,
            f"Accuratezza per Quartili di Entropia ({tag}) — {etich}",
            colore=colore, edge=edge)

"""[10] MaxEnt e Delta entropia per domanda (stabilita' tra ripetizioni)"""

GRUPPO = "Stabilità tra ripetizioni"

for includi_altro in (False, True):
    n_cls = K + (1 if includi_altro else 0)
    tag = f"{'con' if includi_altro else 'senza'} altro, {n_cls} classi"
    maxent = []
    delta = []
    esiti_row = []
    for riga in res.risultati_per_tabella:
        ents = [entropia(alt.get("probabilita", {}), res.classi, includi_altro)
                for alt in riga["alternative"]]
        if not ents:
            continue
        maxent.append(max(ents))
        delta.append(max(ents) - min(ents))
        esiti_row.append(riga["corretta"])
    plot_corrette_errate(
        maxent, esiti_row,
        f"Entropia massima tra le ripetizioni ({tag}) vs Accuratezza",
        f"MaxEnt [0=Sicuro, 1=Indeciso] ({tag})")
    plot_corrette_errate(
        delta, esiti_row,
        f"Delta entropia (Max - Min, {tag}) vs Accuratezza",
        f"Delta entropia [0=Stabile, >0=Instabile] ({tag})")

"""[11] Log-prob della massa FUORI-TASK (media sulle ripetizioni) vs accuratezza

Per ogni domanda calcoliamo, su ciascuna ripetizione, la frazione di massa di
probabilita' che NON e' una classe valida:
    p_fuori_task = 1 - Σ p(classe valida)
Questo include sia il bucket "altro" sia la massa non catturata dai top-K. NON
rinormalizziamo: il denominatore corretto e' l'unita'. Si lavora in log-prob
(ln) su asse lineare con floor a 1e-4, poi si media sulle ripetizioni.
"""

GRUPPO = "Massa fuori-task"

EPS = 1e-4  # floor: sotto questa soglia la massa fuori-task e' trascurabile
logp_fuori = []
esiti_row = []
for riga in res.risultati_per_tabella:
    valori_riga = []
    for alt in riga["alternative"]:
        prob = alt.get("probabilita", {})
        if sum(prob.values()) <= 0:
            continue
        p_valide = sum(prob.get(c, 0.0) for c in res.classi)
        p_fuori = min(1.0, max(EPS, 1.0 - p_valide))
        valori_riga.append(p_fuori)
    if not valori_riga:
        continue
    logp_fuori.append(float(np.log(float(np.mean(valori_riga)))))
    esiti_row.append(riga["corretta"])

if logp_fuori:
    plot_corrette_errate(
        logp_fuori, esiti_row,
        "Log-prob massa FUORI-TASK (media ripetizioni) vs Accuratezza",
        "ln(1 - Σ p_classi_valide)",
        ylim=None)
else:
    print("⚠️ Nessun dato valido per il log-prob fuori-task.")

"""[12] Divergenza KL simmetrizzata tra le ripetizioni (per ora solo stampa)

Come da indicazione del relatore: per ogni domanda si calcola la KL
simmetrizzata su tutte le coppie DISTINTE di ripetizioni (originale inclusa,
n(n-1)/2 coppie) e si prende la distanza MASSIMA. KL ~ 0 = il modello risponde
con la stessa distribuzione a prescindere dalla formulazione; KL alta = almeno
una coppia di formulazioni sposta nettamente la risposta.

La coppia che realizza il massimo viene mostrata in dettaglio dalla sezione
[14] come tabella in galleria; qui si salva in ``coppia_max_kl``.
"""

coppia_max_kl = {}  # includi_altro -> (kl, riga, i, j)

print("\n" + "=" * 78)
print("DIVERGENZA KL SIMMETRIZZATA — MAX SULLE COPPIE (log in base al n. di classi)")
for includi_altro in (False, True):
    n_cls = K + (1 if includi_altro else 0)
    tag = f"{'con' if includi_altro else 'senza'} altro, {n_cls} classi"
    n_domande = 0
    migliore = None  # (kl, riga, i, j) della coppia con la distanza massima
    for riga in res.risultati_per_tabella:
        alts = [a.get("probabilita", {}) for a in riga["alternative"]]
        if len(alts) < 2:
            continue
        n_domande += 1
        for i in range(len(alts)):
            for j in range(i + 1, len(alts)):
                kl = kl_simmetrica(alts[i], alts[j], res.classi, includi_altro)
                if migliore is None or kl > migliore[0]:
                    migliore = (kl, riga, i, j)
    if migliore is None:
        print(f"⚠️ Nessun dato valido per la KL ({tag}).")
        continue
    coppia_max_kl[includi_altro] = migliore
    print(f"KLsym massima ({tag}) su {n_domande} domande: {migliore[0]:.4f}")

"""[13] Tabella Pearson: i 9 descrittori del relatore vs esito (maggioranza)

Per ogni descrittore, Pearson r contro l'esito codificato come 0=corretta,
1=errata (stessa convenzione dei grafici: r > 0 = descrittore piu' alto sulle
domande sbagliate). La tabella entra nella galleria come pagina di grafici.
"""

GRUPPO = "Tabella Pearson"

for includi_altro in (False, True):
    n_cls = K + (1 if includi_altro else 0)
    tag = f"{'con' if includi_altro else 'senza'} altro, {n_cls} classi"
    descr, esiti = descrittori_per_domanda(res, includi_altro)
    if len(esiti) < 2:
        print(f"⚠️ Dati insufficienti per la tabella Pearson ({tag}).")
        continue
    corr = [0 if ok else 1 for ok in esiti]
    righe = []
    for nome, valori in descr.items():
        pr = stats.pearsonr(valori, corr)
        righe.append((nome, pr.statistic, pr.pvalue))
    i_max = max(range(len(righe)), key=lambda i: abs(righe[i][1]))

    fig, ax = plt.subplots(figsize=(9, 5.5), dpi=100)
    ax.axis('off')
    celle = [[nome, f"{r:+.4f}"] for nome, r, _p in righe]
    tab = ax.table(cellText=celle,
                   colLabels=["Descrittore", "r"],
                   colWidths=[0.72, 0.28],
                   cellLoc='center', loc='center')
    tab.auto_set_font_size(False)
    tab.set_fontsize(10)
    tab.scale(1, 1.6)
    for (r_i, c_i), cella in tab.get_celld().items():
        if r_i == 0:
            cella.set_text_props(fontweight='bold', color='white')
            cella.set_facecolor('#37474F')
        else:
            if r_i % 2 == 0:
                cella.set_facecolor('#ECEFF1')
            if c_i == 0:
                cella._loc = 'left'
            if r_i == i_max + 1:
                cella.set_text_props(fontweight='bold')
    ax.set_title(f"Pearson descrittori vs esito (maggioranza) — {tag}", pad=15)
    fig.text(0.5, 0.05,
             f"esito: 0=corretta, 1=errata — "
             f"n={len(esiti)} domande — in grassetto il |r| massimo",
             ha='center', fontsize=9, style='italic', color='#546E7A')
    plt.show()

"""[14] La coppia di distribuzioni con la KL massima globale (tabella in galleria)

Pagina della galleria (una per regime) con una tabella a due righe, una per
formulazione della coppia trovata dalla sezione [12] (``coppia_max_kl``):
numero ripetizione, testo della domanda, una colonna di probabilita' per
classe (rinormalizzata sulle chiavi considerate) ed entropia. Il valore del
max KL sta nel titolo.
"""

GRUPPO = "Coppia max KL"

for includi_altro in (False, True):
    if includi_altro not in coppia_max_kl:
        continue
    n_cls = K + (1 if includi_altro else 0)
    tag = f"{'con' if includi_altro else 'senza'} altro, {n_cls} classi"
    chiavi = list(res.classi) + (["altro"] if includi_altro else [])
    kl, riga, i, j = coppia_max_kl[includi_altro]

    celle = []
    risposte = []
    for idx in (i, j):
        alt = riga["alternative"][idx]
        prob = alt.get("probabilita", {})
        somma = sum(prob.get(c, 0.0) for c in chiavi)
        valori = [prob.get(c, 0.0) / somma if somma > 0 else 0.0 for c in chiavi]
        ent = entropia(prob, res.classi, includi_altro)
        nome = "originale" if idx == 0 else f"parafrasi {idx}"
        risposte.append(f"rip. {idx} → {alt.get('risposta_pulita', '?')}")
        testo = textwrap.fill(str(alt.get("domanda_alt", "?")), width=55)
        # Per le permutazioni il testo e' identico tra le ripetizioni: cio' che
        # cambia e' l'ordine delle opzioni, salvato dal motore in "ordine".
        if alt.get("ordine"):
            testo += "\nordine opzioni: " + " ".join(alt["ordine"])
        celle.append(
            [f"{idx} ({nome})", testo]
            + [f"{v:.4f}" if v == 0 or v >= 0.001 else f"{v:.1e}" for v in valori]
            + [f"{ent:.4f}"])

    fig, ax = plt.subplots(figsize=(12, 3.6), dpi=100)
    ax.axis('off')
    tab = ax.table(cellText=celle,
                   colLabels=["Ripetizione", "Testo domanda"]
                             + [f"%{c}" for c in chiavi] + ["Entropia"],
                   colWidths=[0.13, 0.45] + [0.32 / len(chiavi)] * len(chiavi) + [0.10],
                   cellLoc='center', loc='center')
    tab.auto_set_font_size(False)
    tab.set_fontsize(10)
    tab.scale(1, 3.0)
    for (r_i, c_i), cella in tab.get_celld().items():
        if r_i == 0:
            cella.set_text_props(fontweight='bold', color='white')
            cella.set_facecolor('#37474F')
        else:
            if r_i % 2 == 0:
                cella.set_facecolor('#ECEFF1')
            if c_i == 1:
                cella._loc = 'left'
    ax.set_title(f"Coppia di ripetizioni con KL massima ({tag}) — KLsym = {kl:.4f}",
                 pad=15)
    fig.text(0.5, 0.04,
             f"domanda id={riga['id']} — risposta reale: {riga['reale']} — "
             f"risposte del modello: {', '.join(risposte)} — "
             f"probabilità rinormalizzate sulle classi considerate",
             ha='center', fontsize=9, style='italic', color='#546E7A')
    plt.show()

"""[15] Curva accuracy-rejection: accuratezza vs frazione di domande tenute

Richiesta del relatore (2026-07-21): se una misura di incertezza M e'
informativa, le risposte con M alta tendono a essere sbagliate. Si ordinano
quindi le domande per M crescente e si calcola l'accuratezza sul primo x%
(le piu' "sicure"): X = frazione del dataset tenuta, Y = accuratezza sulle
domande tenute. Al diminuire di x l'accuratezza dovrebbe salire.
Una figura per regime (senza / con "altro") con le curve dei 9 descrittori
della sezione [13]; esito = maggioranza.
"""

GRUPPO = "Accuracy-rejection"

FRAZIONI_TENUTE = np.linspace(0.05, 1.0, 20)


def accuratezza_cumulativa(esiti_ordinati):
    """Accuratezza sul primo x% di ``esiti_ordinati``, per x in FRAZIONI_TENUTE."""
    cumulate = np.cumsum(esiti_ordinati)
    acc = []
    for f in FRAZIONI_TENUTE:
        n = max(1, int(round(f * len(esiti_ordinati))))
        acc.append(cumulate[n - 1] / n)
    return acc


for includi_altro in (False, True):
    n_cls = K + (1 if includi_altro else 0)
    tag = f"{'con' if includi_altro else 'senza'} altro, {n_cls} classi"
    descr, esiti = descrittori_per_domanda(res, includi_altro)
    if len(esiti) < 2:
        print(f"⚠️ Dati insufficienti per la curva accuracy-rejection ({tag}).")
        continue
    esiti_num = np.asarray(esiti, dtype=float)

    fig, ax = plt.subplots(figsize=(10, 6), dpi=100)
    colori = plt.get_cmap('tab10')
    for k, (nome, valori) in enumerate(descr.items()):
        ordine = np.argsort(valori, kind="stable")
        ax.plot(FRAZIONI_TENUTE, accuratezza_cumulativa(esiti_num[ordine]),
                color=colori(k % 10), linewidth=1.6, label=nome)
    ax.set_title(f"Accuracy-rejection — accuratezza vs frazione tenuta ({tag})",
                 pad=15)
    ax.set_xlabel("Frazione del dataset tenuta (dal descrittore più basso)")
    ax.set_ylabel("Accuratezza (risposta di maggioranza)")
    ax.grid(linestyle='--', alpha=0.7)
    ax.legend(fontsize=8, loc='upper left', bbox_to_anchor=(1.01, 1),
              title="ordinamento per", title_fontsize=9)
    plt.tight_layout()
    plt.show()
    print(f"  Accuracy-rejection ({tag}): n={len(esiti_num)} domande, "
          f"accuratezza globale {esiti_num.mean():.4f}")
