# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9zjz6AGpKScwIXG_ngGuoyQz1NVYbNO

[1] Import librerie
"""

import csv
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.ticker import MultipleLocator
from google.colab import files
from scipy import stats
from scipy.stats import entropy as scipy_entropy

"""[2] Costanti di visualizzazione"""

NUM_TEST = 3000
RIPETIZIONI_PER_DOMANDA = 5

"""[3] Caricamento"""

print("Seleziona il file CSV con i risultati del benchmark:")
uploaded = files.upload()

# Recupera il nome del file appena caricato
if uploaded:
    NOME_FILE = list(uploaded.keys())[0]
    print(f"\nFile '{NOME_FILE}' caricato con successo!")
else:
    print("\nNessun f ile caricato. Assicurati di selezionare il file prima di procedere.")

"""[4] Analizzatore di benchmark su accuratezza e entropia"""

def calcola_entropia_ternaria(p_true: float, p_false: float, p_other: float) -> float:
    somma = p_true + p_false + p_other
    if somma <= 0:
        return 0.0

    p_t = p_true / somma
    p_f = p_false / somma
    p_o = p_other / somma

    # Usare base=3 fissa il limite massimo esattamente a 1.0
    return scipy_entropy([p_t, p_f, p_o], base=3)

def calcola_entropia_binaria(p_true: float, p_false: float) -> float:
    somma = p_true + p_false
    if somma <= 0:
        return 0.0
    # Normalizziamo ignorando p_other
    p_t = p_true / somma
    p_f = p_false / somma

    return scipy_entropy([p_t, p_f], base=2)

class RisultatiBenchmark:
    def __init__(self):
        # Matrice di confusione del VOTO DI MAGGIORANZA
        self.tp, self.tn, self.fp, self.fn = 0, 0, 0, 0
        # Matrice di confusione ORIGINALE
        self.tp_orig, self.tn_orig, self.fp_orig, self.fn_orig = 0, 0, 0, 0
        # Matrice di confusione MODIFICATE
        self.tp_mod, self.tn_mod, self.fp_mod, self.fn_mod = 0, 0, 0, 0

        self.risultati_per_tabella = []
        self.dist_corrette = {}
        self.dist_errate = {}

def carica_da_csv(filename) -> RisultatiBenchmark:
    risultati = RisultatiBenchmark()
    with open(filename, mode='r', encoding='utf-8') as file:
        reader = csv.DictReader(file)
        for row in reader:
            risposta_reale = row["reale"].strip().lower()
            alternative = json.loads(row["alternative_json"])

            # Maggioranza derivata dalle somme grezze delle probabilità
            somma_t = sum(a.get("p_true_raw", 0.0) for a in alternative)
            somma_f = sum(a.get("p_false_raw", 0.0) for a in alternative)
            if somma_t > somma_f:
                risposta_maggioranza = "true"
            elif somma_f > somma_t:
                risposta_maggioranza = "false"
            else:
                risposta_maggioranza = "pareggio"
            esito_corretto = (risposta_maggioranza == risposta_reale)

            # Distribuzione dei voti per maggioranza (es. "5-0", "3-2", ecc.)
            conteggi = {"true": 0, "false": 0, "altri": 0}
            for a in alternative:
                risp = a["risposta_pulita"].strip().lower()
                conteggi[risp if risp in conteggi else "altri"] += 1
            valori = sorted([conteggi["true"], conteggi["false"]], reverse=True)
            generata_dist = f"{valori[0]}-{valori[1]}"

            # ORIGINALE (Indice 0)
            risposta_originale = alternative[0]["risposta_pulita"].strip().lower()
            if risposta_originale == "true" and risposta_reale == "true": risultati.tp_orig += 1
            elif risposta_originale == "false" and risposta_reale == "false": risultati.tn_orig += 1
            elif risposta_originale == "true" and risposta_reale == "false": risultati.fp_orig += 1
            elif risposta_originale == "false" and risposta_reale == "true": risultati.fn_orig += 1

            # MODIFICATE (Indici da 1 a 4)
            for alt in alternative[1:]:
                risp_mod = alt["risposta_pulita"].strip().lower()
                if risp_mod == "true" and risposta_reale == "true": risultati.tp_mod += 1
                elif risp_mod == "false" and risposta_reale == "false": risultati.tn_mod += 1
                elif risp_mod == "true" and risposta_reale == "false": risultati.fp_mod += 1
                elif risp_mod == "false" and risposta_reale == "true": risultati.fn_mod += 1

            # MAGGIORANZA
            if esito_corretto:
                risultati.dist_corrette[generata_dist] = risultati.dist_corrette.get(generata_dist, 0) + 1
                if risposta_reale == "true": risultati.tp += 1
                else: risultati.tn += 1
            else:
                risultati.dist_errate[generata_dist] = risultati.dist_errate.get(generata_dist, 0) + 1
                if risposta_reale == "false": risultati.fp += 1
                else: risultati.fn += 1

            risultati.risultati_per_tabella.append({
                "id": int(row["id"]),
                "domanda": row["domanda"],
                "reale": risposta_reale,
                "alternative": alternative,
                "generata_dist": generata_dist,
                "corretta": esito_corretto
            })
    return risultati

def analyzer(risultati: RisultatiBenchmark) -> RisultatiBenchmark:
    for riga in risultati.risultati_per_tabella:
        entropie_binarie = []
        entropie_ternarie = []
        somma_norm_t = 0.0
        somma_norm_f = 0.0

        for alt in riga["alternative"]:
            p_t = alt.get("p_true_raw", 0.0)
            p_f = alt.get("p_false_raw", 0.0)
            p_o = alt.get("p_altri_raw", 0.0)

            ent_ternaria = calcola_entropia_ternaria(p_t, p_f, p_o)
            entropie_ternarie.append(ent_ternaria)

            # Calcolo entropia binaria per min/max
            ent_binaria = calcola_entropia_binaria(p_t, p_f)
            entropie_binarie.append(ent_binaria)

            # Accumulo per la media della distribuzione
            somma_binaria = p_t + p_f
            if somma_binaria > 0:
                somma_norm_t += p_t / somma_binaria
                somma_norm_f += p_f / somma_binaria

        k = len(riga["alternative"])
        if k > 0:
            # Metriche binarie normalizzate su True/False
            riga["min_ent"] = min(entropie_binarie)
            riga["max_ent"] = max(entropie_binarie)

            # avg_ent: entropia della media delle distribuzioni binarie
            riga["avg_ent"] = scipy_entropy(
                [somma_norm_t / k, somma_norm_f / k],
                base=2
            )

            # Salviamo anche le entropie ternarie per estrarle facilmente nei grafici
            riga["entropie_ternarie"] = entropie_ternarie
        else:
            riga["min_ent"], riga["max_ent"], riga["avg_ent"] = 0.0, 0.0, 0.0
            riga["entropie_ternarie"] = []

    return risultati

"""# MATRICI CONFUSIONI E PRECISION

[5] Grafico accuratezza e confusion matrix della domanda originale/varianti/miste
"""

def stampa_matrice(tp, tn, fp, fn, titolo):
    fig, ax = plt.subplots(figsize=(4, 3.2))
    ax.set_xlim(0, 3)
    ax.set_ylim(0, 3)
    ax.axis('off')

    ax.text(1.5, 2.85, titolo, ha='center', va='center',
            fontsize=12, fontweight='bold')

    ax.text(1.5, 2.55, "Modello: T", ha='center', va='center', fontsize=10)
    ax.text(2.5, 2.55, "Modello: F", ha='center', va='center', fontsize=10)

    ax.text(0.5, 1.75, "Realtà: T", ha='center', va='center', fontsize=10)
    ax.text(0.5, 0.75, "Realtà: F", ha='center', va='center', fontsize=10)

    verde = "#c6efce"
    rosso = "#ffc7ce"
    verde_testo = "#006100"
    rosso_testo = "#9c0006"

    celle = [
        (1.0, 1.25, verde, verde_testo, "TP", tp),
        (2.0, 1.25, rosso, rosso_testo, "FN", fn),
        (1.0, 0.25, rosso, rosso_testo, "FP", fp),
        (2.0, 0.25, verde, verde_testo, "TN", tn),
    ]

    for (x, y, bg, fg, label, val) in celle:
        rect = mpatches.FancyBboxPatch(
            (x, y), 0.9, 0.9,
            boxstyle="square,pad=0.02",
            linewidth=1, edgecolor='gray',
            facecolor=bg
        )
        ax.add_patch(rect)
        ax.text(x + 0.45, y + 0.62, label,
                ha='center', va='center',
                fontsize=11, fontweight='bold', color=fg)
        ax.text(x + 0.45, y + 0.28, str(val),
                ha='center', va='center',
                fontsize=13, fontweight='bold', color=fg)

    plt.tight_layout()
    plt.show()


# Processa i dati
res = carica_da_csv(NOME_FILE)
res = analyzer(res)

tot_orig = res.tp_orig + res.tn_orig + res.fp_orig + res.fn_orig
tot_magg = res.tp + res.tn + res.fp + res.fn
tot_mod = res.tp_mod + res.tn_mod + res.fp_mod + res.fn_mod

# Calcoli accuratezza
acc_orig = ((res.tp_orig + res.tn_orig) / tot_orig) * 100 if NUM_TEST > 0 else 0
acc_mod = ((res.tp_mod + res.tn_mod) / tot_mod) * 100 if tot_mod > 0 else 0
acc_maggioranza = ((res.tp + res.tn) / tot_magg) * 100 if NUM_TEST > 0 else 0

print(f"ACCURATEZZA ORIGINALI: {acc_orig:.4f}% | VARIANTI: {acc_mod:.4f}% | MAGGIORANZA: {acc_maggioranza:.4f}%")

stampa_matrice(res.tp_orig, res.tn_orig, res.fp_orig, res.fn_orig, f"Originale ({acc_orig:.1f}%)")
stampa_matrice(res.tp_mod,  res.tn_mod,  res.fp_mod,  res.fn_mod,  f"Varianti ({acc_mod:.1f}%)")
stampa_matrice(res.tp,      res.tn,      res.fp,      res.fn,      f"Maggioranza ({acc_maggioranza:.1f}%)")

def stampa_metriche(tp, tn, fp, fn, nome):
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall    = tp / (tp + fn) if (tp + fn) > 0 else 0
    accuracy  = (tp + tn) / (tp + tn + fp + fn) if (tp + tn + fp + fn) > 0 else 0

    print(f"--- {nome} ---")
    print(f"Accuracy : {accuracy:.4f}")
    # Quando il modello dice TRUE, quante volte ha ragione?
    print(f"Precision: {precision:.4f}")
    # Di tutti i TRUE reali, quanti ne ha trovati il modello?
    print(f"Recall   : {recall:.4f}")
    print()

stampa_metriche(res.tp_orig, res.tn_orig, res.fp_orig, res.fn_orig, "Originale")
stampa_metriche(res.tp_mod,  res.tn_mod,  res.fp_mod,  res.fn_mod,  "Varianti")
stampa_metriche(res.tp,      res.tn,      res.fp,      res.fn,      "Maggioranza")

"""# ENTROPIA MASSIMA E MEDIA, RISPOSTE CORRETTE/SBAGLIATE

[8] Distribuzione MaxEnt per Domande Corrette ed Errate
"""

max_ent_corrette = [r.get("max_ent", 0.0) for r in res.risultati_per_tabella if r["corretta"]]
max_ent_errate = [r.get("max_ent", 0.0) for r in res.risultati_per_tabella if not r["corretta"]]

fig, ax = plt.subplots(figsize=(8, 5), dpi=100)
dati_max = [max_ent_corrette if max_ent_corrette else [0.0], max_ent_errate if max_ent_errate else [0.0]]
bplot = ax.boxplot(dati_max, labels=['Corrette', 'Errate'], patch_artist=True)

colors = ['#4CAF50', '#F44336']
for patch, color in zip(bplot['boxes'], colors):
    patch.set_facecolor(color)
    patch.set_alpha(0.7)

ax.set_title("Distribuzione MaxEnt per Domande Corrette ed Errate")
ax.set_ylabel("Entropia Massima (MaxEnt)")
ax.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""[9] Distribuzione AvgEnt per Domande Corrette ed Errate"""

avg_ent_corrette = [r.get("avg_ent", 0.0) for r in res.risultati_per_tabella if r["corretta"]]
avg_ent_errate = [r.get("avg_ent", 0.0) for r in res.risultati_per_tabella if not r["corretta"]]

fig, ax = plt.subplots(figsize=(8, 5), dpi=100)
dati_avg = [avg_ent_corrette if avg_ent_corrette else [0.0], avg_ent_errate if avg_ent_errate else [0.0]]
bplot = ax.boxplot(dati_avg, labels=['Corrette', 'Errate'], patch_artist=True)

colors = ['#4CAF50', '#F44336']
for patch, color in zip(bplot['boxes'], colors):
    patch.set_facecolor(color)
    patch.set_alpha(0.7)

ax.set_title("Distribuzione AvgEnt per Domande Corrette ed Errate")
ax.set_ylabel("Entropia Media (AvgEnt) [0.0 - 1.0]")
ax.set_ylim(-0.05, 1.05)
ax.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""# DOMANDE ORIGINALI

[11]
"""

# Liste per separare le entropie
entropie_corrette_orig = []
entropie_errate_orig = []
vettore_correttezza = []  # 0 se corretta, 1 se sbagliata
vettore_entropia = []     # Valore dell'entropia corrispondente

if 'res' in locals() and res.risultati_per_tabella:

    for riga in res.risultati_per_tabella:
        # Estraiamo SOLO la domanda originale (indice 0 della lista alternative)
        alt_orig = riga["alternative"][0]

        # Calcolo Entropia di Shannon tramite funzione
        ent = calcola_entropia_binaria(alt_orig.get("p_true_raw", 0.0), alt_orig.get("p_false_raw", 0.0))
        # Verifichiamo se LA RISPOSTA ORIGINALE era corretta o sbagliata
        risp_orig = alt_orig["risposta_pulita"].strip().lower()
        risp_reale = riga["reale"].strip().lower()

        vettore_entropia.append(ent)
        if risp_orig == risp_reale:
            entropie_corrette_orig.append(ent)
            vettore_correttezza.append(0)
        else:
            entropie_errate_orig.append(ent)
            vettore_correttezza.append(1)

    fig, ax = plt.subplots(figsize=(8, 6), dpi=100)

    data_to_plot = [entropie_corrette_orig, entropie_errate_orig]

    bp = ax.boxplot(data_to_plot, positions=[1, 2], widths=0.4, patch_artist=True, showfliers=False, zorder=1)

    box_colors = ['#FFFFFF', '#FFFFFF']
    box_edges = ['#4CAF50', '#F44336']

    for patch, color, edge in zip(bp['boxes'], box_colors, box_edges):
        patch.set_facecolor(color)
        patch.set_edgecolor(edge)
        patch.set_linewidth(1.5)

    for median in bp['medians']:
        median.set(color='black', linewidth=2)

    jitter_corrette = np.random.normal(1, 0.05, size=len(entropie_corrette_orig))
    jitter_errate = np.random.normal(2, 0.05, size=len(entropie_errate_orig))

    ax.scatter(jitter_corrette, entropie_corrette_orig, alpha=0.6, color='#4CAF50',
               edgecolors='white', linewidth=0.5, label=f'Esatte ({len(entropie_corrette_orig)})', zorder=2)

    ax.scatter(jitter_errate, entropie_errate_orig, alpha=0.6, color='#F44336',
               edgecolors='white', linewidth=0.5, label=f'Sbagliate ({len(entropie_errate_orig)})', zorder=2)

    ax.set_xticks([1, 2])
    ax.set_xticklabels(['Risposte Esatte', 'Risposte Sbagliate'], fontsize=11, fontweight='bold')
    ax.set_title("Distribuzione dell'Entropia (Domanda Originale) in base all'Accuratezza", pad=15)
    ax.set_ylabel("Entropia [0.0 = Sicuro, 1.0 = Indeciso]")
    ax.set_ylim(-0.05, 1.05)
    ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=2)
    ax.grid(axis='y', linestyle='--', alpha=0.7, zorder=0)

    pearson_result = stats.pearsonr(vettore_entropia, vettore_correttezza)
    print(f"Coefficiente di correlazione di Pearson: {pearson_result.statistic}")

    plt.show()

else:
    print("⚠️ Dati non trovati. Assicurati di aver eseguito i blocchi precedenti per caricare il CSV nell'oggetto 'res'.")

"""[12]"""

if 'res' in locals() and res.risultati_per_tabella:

    dati_estratti = []

    for riga in res.risultati_per_tabella:
        # Estraiamo SOLO la domanda originale (indice 0)
        alt_orig = riga["alternative"][0]

        # Calcolo Entropia per la domanda originale
        ent = calcola_entropia_binaria(alt_orig.get("p_true_raw", 0.0), alt_orig.get("p_false_raw", 0.0))

        # Verifichiamo se la risposta era corretta
        risp_orig = alt_orig["risposta_pulita"].strip().lower()
        risp_reale = riga["reale"].strip().lower()
        esito = (risp_orig == risp_reale)

        dati_estratti.append({"entropia": ent, "corretto": esito})

    # CALCOLO QUARTILI: Estraiamo solo le entropie
    entropie = [d["entropia"] for d in dati_estratti]

    # Calcoliamo i limiti dei 4 quartili (0%, 25%, 50%, 75%, 100%)
    limiti_quartili = np.percentile(entropie, [0, 25, 50, 75, 100])

    # Creiamo le etichette indicando Q1, Q2, Q3, Q4 e i rispettivi range
    etichette_bins = [f"Q{i+1}\n({limiti_quartili[i]:.4f} - {limiti_quartili[i+1]:.4f})" for i in range(4)]

    corrette_per_bin = [0] * 4
    totali_per_bin = [0] * 4

    for dato in dati_estratti:
        ent = dato["entropia"]

        indice_bin = np.digitize(ent, limiti_quartili) - 1

        indice_bin = min(max(indice_bin, 0), 3)

        totali_per_bin[indice_bin] += 1
        if dato["corretto"]:
            corrette_per_bin[indice_bin] += 1

    # Calcolo Accuratezza percentuale per ogni quartile
    accuratezze = []
    for c, t in zip(corrette_per_bin, totali_per_bin):
        if t > 0:
            accuratezze.append((c / t) * 100)
        else:
            accuratezze.append(0.0)

    fig, ax = plt.subplots(figsize=(9, 5), dpi=100)

    barre = ax.bar(etichette_bins, accuratezze, color='#2196F3', alpha=0.8, edgecolor='#1565C0', linewidth=1.5)

    for bar, t in zip(barre, totali_per_bin):
        altezza = bar.get_height()
        ax.annotate(f'{altezza:.2f}%\n(n={t})',
                    xy=(bar.get_x() + bar.get_width() / 2, altezza),
                    xytext=(0, 3), textcoords="offset points",
                    ha='center', va='bottom', fontweight='bold', fontsize=9)

    ax.set_title("Accuratezza per Quartili di Entropia (Solo Domanda Originale)", pad=15)
    ax.set_xlabel("Quartili (Q1 = Più Sicuro  ⟶  Q4 = Più Indeciso)")
    ax.set_ylabel("Accuratezza (%)")
    ax.set_ylim(0, 115)
    ax.grid(axis='y', linestyle='--', alpha=0.7)

    plt.show()

else:
    print("⚠️ Dati non trovati. Assicurati di aver eseguito i blocchi precedenti per caricare il CSV nell'oggetto 'res'.")

"""# DOMANDE MAGGIORANZA

[13]
"""

entropie_corrette_avg = []
entropie_errate_avg = []
vettore_correttezza = []  # 0 se corretta, 1 se sbagliata
vettore_entropia = []     # Valore dell'entropia corrispondente

num_bins = 5
limiti_bins = np.linspace(0, 1, num_bins + 1)
etichette_bins = [f"{limiti_bins[i]:.4f} - {limiti_bins[i+1]:.4f}" for i in range(num_bins)]
corrette_per_bin = [0] * num_bins
totali_per_bin = [0] * num_bins

if 'res' in locals() and res.risultati_per_tabella:

    for riga in res.risultati_per_tabella:
        somma_norm_t = 0.0
        somma_norm_f = 0.0
        k_valide = 0

        # Estrazione e normalizzazione
        for alt in riga["alternative"]:
            p_t = alt.get("p_true_raw", 0.0)
            p_f = alt.get("p_false_raw", 0.0)

            somma_raw = p_t + p_f
            if somma_raw > 0:
                somma_norm_t += p_t / somma_raw
                somma_norm_f += p_f / somma_raw
                k_valide += 1

        if k_valide > 0:
            # Distribuzione media
            media_t = somma_norm_t / k_valide
            media_f = somma_norm_f / k_valide

            # Entropia della media
            ent_media = calcola_entropia_binaria(media_t, media_f)

            risp_predetta = "true" if media_t > media_f else "false"
            risp_reale = riga["reale"].strip().lower()
            esito_corretto = (risp_predetta == risp_reale)

            vettore_entropia.append(ent_media)
            # Raccolta dati
            if esito_corretto:
                entropie_corrette_avg.append(ent_media)
                vettore_correttezza.append(0)
            else:
                entropie_errate_avg.append(ent_media)
                vettore_correttezza.append(1)

            indice_bin = min(int(ent_media * num_bins), num_bins - 1)
            totali_per_bin[indice_bin] += 1
            if esito_corretto:
                corrette_per_bin[indice_bin] += 1

    fig1, ax1 = plt.subplots(figsize=(8, 6), dpi=100)

    data_to_plot = [entropie_corrette_avg, entropie_errate_avg]

    bp = ax1.boxplot(data_to_plot, positions=[1, 2], widths=0.4, patch_artist=True, showfliers=False, zorder=1)

    box_colors = ['#FFFFFF', '#FFFFFF']
    box_edges = ['#4CAF50', '#F44336']

    for patch, color, edge in zip(bp['boxes'], box_colors, box_edges):
        patch.set_facecolor(color)
        patch.set_edgecolor(edge)
        patch.set_linewidth(1.5)

    for median in bp['medians']:
        median.set(color='black', linewidth=2)

    jitter_c = np.random.normal(1, 0.05, size=len(entropie_corrette_avg))
    jitter_e = np.random.normal(2, 0.05, size=len(entropie_errate_avg))

    ax1.scatter(jitter_c, entropie_corrette_avg, alpha=0.6, color='#4CAF50',
                edgecolors='white', linewidth=0.5, label=f'Esatte ({len(entropie_corrette_avg)})', zorder=2)

    ax1.scatter(jitter_e, entropie_errate_avg, alpha=0.6, color='#F44336',
                edgecolors='white', linewidth=0.5, label=f'Sbagliate ({len(entropie_errate_avg)})', zorder=2)

    ax1.set_xticks([1, 2])
    ax1.set_xticklabels(['Risposte Esatte', 'Risposte Sbagliate'], fontsize=11, fontweight='bold')
    ax1.set_title("Scatterplot e Boxplot: Distribuzione dell'Entropia (Risposta di maggioranza) in base all'Accuratezza", pad=15)
    ax1.set_ylabel("Entropia [0.0 = Sicuro, 1.0 = Indeciso]")
    ax1.set_ylim(-0.05, 1.05)
    ax1.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=2)
    ax1.grid(axis='y', linestyle='--', alpha=0.7, zorder=0)

    pearson_result = stats.pearsonr(vettore_entropia, vettore_correttezza)
    print(f"Coefficiente di correlazione di Pearson: {pearson_result.statistic}")

    plt.show()

else:
    print("⚠️ Dati non trovati. Assicurati di aver eseguito i blocchi precedenti per caricare il CSV nell'oggetto 'res'.")

"""[14]"""

if 'totali_per_bin' in locals():

    valori_entropia = [r.get("avg_ent", 0.0) for r in res.risultati_per_tabella]

    limiti_quartili = np.percentile(valori_entropia, [0, 25, 50, 75, 100])

    corrette_per_q = [0] * 4
    totali_per_q = [0] * 4

    for r in res.risultati_per_tabella:
        ent = r.get("avg_ent", 0.0)
        corretta = r.get("corretta", False)

        indice_q = np.digitize(ent, limiti_quartili) - 1
        indice_q = min(max(indice_q, 0), 3)

        totali_per_q[indice_q] += 1
        if corretta:
            corrette_per_q[indice_q] += 1

    # Calcolo dell'accuratezza percentuale per quartile
    accuratezze = []
    for c, t in zip(corrette_per_q, totali_per_q):
        if t > 0:
            accuratezze.append((c / t) * 100)
        else:
            accuratezze.append(0.0)

    fig, ax = plt.subplots(figsize=(8, 5), dpi=100)

    etichette_q = [f"Q{i+1}\n({limiti_quartili[i]:.4f} - {limiti_quartili[i+1]:.4f})" for i in range(4)]

    barre = ax.bar(etichette_q, accuratezze, color='#2196F3', alpha=0.85,
                   edgecolor='#1565C0', linewidth=1.2, width=0.6)

    for bar, acc, n in zip(barre, accuratezze, totali_per_q):
        ax.annotate(f'{acc:.2f}%\n(n={n})',
                    xy=(bar.get_x() + bar.get_width() / 2, acc),
                    xytext=(0, 5), textcoords="offset points",
                    ha='center', va='bottom', fontweight='bold', fontsize=11)

    ax.set_title("Accuratezza per quartili di Entropia (Domanda di maggioranza)", pad=15)
    ax.set_ylabel("Accuratezza (%)")
    ax.set_ylim(0, 115)
    ax.grid(axis='y', linestyle='--', alpha=0.7)
    ax.legend()
    plt.show()

else:
    print("⚠️ Dati non trovati. Esegui prima il blocco 6.1 per generare i conteggi.")

"""#TUTTE LE DOMANDE

"""

entropie_corrette_all = []
entropie_errate_all = []
vettore_correttezza_all = []  # 0 se corretta, 1 se sbagliata
vettore_entropia_all = []     # Valore dell'entropia corrispondente

if 'res' in locals() and res.risultati_per_tabella:

    for riga in res.risultati_per_tabella:
        for alt in riga["alternative"]:

            p_t = alt.get("p_true_raw", 0.0)
            p_f = alt.get("p_false_raw", 0.0)
            ent = calcola_entropia_binaria(p_t, p_f)

            risp_alt = alt.get("risposta_pulita", "").strip().lower()
            risp_reale = riga["reale"].strip().lower()

            vettore_entropia_all.append(ent)

            if risp_alt == risp_reale:
                entropie_corrette_all.append(ent)
                vettore_correttezza_all.append(0)
            else:
                entropie_errate_all.append(ent)
                vettore_correttezza_all.append(1)

    fig, ax = plt.subplots(figsize=(8, 6), dpi=100)

    data_to_plot = [entropie_corrette_all, entropie_errate_all]

    bp = ax.boxplot(data_to_plot, positions=[1, 2], widths=0.4, patch_artist=True, showfliers=False, zorder=1)

    box_colors = ['#FFFFFF', '#FFFFFF']
    box_edges = ['#4CAF50', '#F44336']

    for patch, color, edge in zip(bp['boxes'], box_colors, box_edges):
        patch.set_facecolor(color)
        patch.set_edgecolor(edge)
        patch.set_linewidth(1.5)

    for median in bp['medians']:
        median.set(color='black', linewidth=2)

    jitter_corrette = np.random.normal(1, 0.05, size=len(entropie_corrette_all))
    jitter_errate = np.random.normal(2, 0.05, size=len(entropie_errate_all))

    ax.scatter(jitter_corrette, entropie_corrette_all, alpha=0.5, color='#4CAF50',
               edgecolors='white', linewidth=0.5, label=f'Esatte ({len(entropie_corrette_all)})', zorder=2)

    ax.scatter(jitter_errate, entropie_errate_all, alpha=0.5, color='#F44336',
               edgecolors='white', linewidth=0.5, label=f'Sbagliate ({len(entropie_errate_all)})', zorder=2)

    ax.set_xticks([1, 2])
    ax.set_xticklabels(['Risposte Esatte', 'Risposte Sbagliate'], fontsize=11, fontweight='bold')
    ax.set_title("Distribuzione Entropia (Originale + Varianti) vs Accuratezza", pad=15)
    ax.set_ylabel("Entropia [0.0 = Sicuro, 1.0 = Indeciso]")
    ax.set_ylim(-0.05, 1.05)
    ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=2)
    ax.grid(axis='y', linestyle='--', alpha=0.7, zorder=0)

    if len(vettore_entropia_all) > 1:
        pearson_result = stats.pearsonr(vettore_entropia_all, vettore_correttezza_all)
        print(f"Coefficiente di correlazione di Pearson: {pearson_result.statistic}")

    plt.show()

else:
    print("⚠️ Dati non trovati. Assicurati di aver eseguito i blocchi precedenti per caricare il CSV nell'oggetto 'res'.")

if 'res' in locals() and res.risultati_per_tabella:

    dati_estratti_all = []

    for riga in res.risultati_per_tabella:
        for alt in riga["alternative"]:

            ent = calcola_entropia_binaria(alt.get("p_true_raw", 0.0), alt.get("p_false_raw", 0.0))

            risp_alt = alt.get("risposta_pulita", "").strip().lower()
            risp_reale = riga["reale"].strip().lower()
            esito = (risp_alt == risp_reale)

            dati_estratti_all.append({"entropia": ent, "corretto": esito})

    entropie_all = [d["entropia"] for d in dati_estratti_all]

    limiti_quartili = np.percentile(entropie_all, [0, 25, 50, 75, 100])

    etichette_bins = [f"Q{i+1}\n({limiti_quartili[i]:.4f} - {limiti_quartili[i+1]:.4f})" for i in range(4)]

    corrette_per_bin = [0] * 4
    totali_per_bin = [0] * 4

    for dato in dati_estratti_all:
        ent = dato["entropia"]

        indice_bin = np.digitize(ent, limiti_quartili) - 1

        indice_bin = min(max(indice_bin, 0), 3)

        totali_per_bin[indice_bin] += 1
        if dato["corretto"]:
            corrette_per_bin[indice_bin] += 1

    accuratezze = []
    for c, t in zip(corrette_per_bin, totali_per_bin):
        if t > 0:
            accuratezze.append((c / t) * 100)
        else:
            accuratezze.append(0.0)

    fig, ax = plt.subplots(figsize=(9, 5), dpi=100)

    barre = ax.bar(etichette_bins, accuratezze, color='#2196F3', alpha=0.8, edgecolor='#1565C0', linewidth=1.5)

    for bar, t in zip(barre, totali_per_bin):
        altezza = bar.get_height()
        ax.annotate(f'{altezza:.2f}%\n(n={t})',
                    xy=(bar.get_x() + bar.get_width() / 2, altezza),
                    xytext=(0, 3), textcoords="offset points",
                    ha='center', va='bottom', fontweight='bold', fontsize=9)

    ax.set_title("Accuratezza per Quartili di Entropia (Originale + Tutte le Varianti)", pad=15)
    ax.set_xlabel("Quartili (Q1 = Più Sicuro  ⟶  Q4 = Più Indeciso)")
    ax.set_ylabel("Accuratezza (%)")
    ax.set_ylim(0, 115)
    ax.grid(axis='y', linestyle='--', alpha=0.7)

    plt.show()

else:
    print("⚠️ Dati non trovati. Assicurati di aver eseguito i blocchi precedenti per caricare il CSV nell'oggetto 'res'.")

"""# DISTRIBUZIONI TERNARIE SU ORIGINALI

[15]
"""

entropie_corrette_ter = []
entropie_errate_ter = []
vettore_correttezza = []  # 0 se corretta, 1 se sbagliata
vettore_entropia = []     # Valore dell'entropia corrispondente

num_bins = 5
limiti_bins = np.linspace(0, 1, num_bins + 1)
etichette_bins = [f"{limiti_bins[i]:.4f} - {limiti_bins[i+1]:.4f}" for i in range(num_bins)]
corrette_per_bin = [0] * num_bins
totali_per_bin = [0] * num_bins


if 'res' in locals() and res.risultati_per_tabella:

    for riga in res.risultati_per_tabella:
        alt_orig = riga["alternative"][0]

        p_t = alt_orig.get("p_true_raw", 0.0)
        p_f = alt_orig.get("p_false_raw", 0.0)
        p_o = alt_orig.get("p_altri_raw",0.0)

        ent_norm = calcola_entropia_ternaria(p_t, p_f, p_o)

        risp_orig = alt_orig["risposta_pulita"].strip().lower()
        risp_reale = riga["reale"].strip().lower()
        esito = (risp_orig == risp_reale)

        vettore_entropia.append(ent_norm)
        if esito:
            entropie_corrette_ter.append(ent_norm)
            vettore_correttezza.append(0)
        else:
            entropie_errate_ter.append(ent_norm)
            vettore_correttezza.append(1)

        indice_bin = min(int(ent_norm * num_bins), num_bins - 1)
        totali_per_bin[indice_bin] += 1
        if esito:
            corrette_per_bin[indice_bin] += 1

    fig1, ax1 = plt.subplots(figsize=(8, 6), dpi=100)

    data_to_plot = [entropie_corrette_ter, entropie_errate_ter]

    bp = ax1.boxplot(data_to_plot, positions=[1, 2], widths=0.4, patch_artist=True, showfliers=False, zorder=1)

    box_colors = ['#FFFFFF', '#FFFFFF']
    box_edges = ['#4CAF50', '#F44336']

    for patch, color, edge in zip(bp['boxes'], box_colors, box_edges):
        patch.set_facecolor(color)
        patch.set_edgecolor(edge)
        patch.set_linewidth(1.5)

    for median in bp['medians']:
        median.set(color='black', linewidth=2)

    jitter_c = np.random.normal(1, 0.05, size=len(entropie_corrette_ter))
    jitter_e = np.random.normal(2, 0.05, size=len(entropie_errate_ter))

    ax1.scatter(jitter_c, entropie_corrette_ter, alpha=0.6, color='#4CAF50',
                edgecolors='white', linewidth=0.5, label=f'Esatte ({len(entropie_corrette_ter)})', zorder=2)
    ax1.scatter(jitter_e, entropie_errate_ter, alpha=0.6, color='#F44336',
                edgecolors='white', linewidth=0.5, label=f'Sbagliate ({len(entropie_errate_ter)})', zorder=2)

    ax1.set_xticks([1, 2])
    ax1.set_xticklabels(['Risposte Esatte', 'Risposte Sbagliate'], fontsize=11, fontweight='bold')
    ax1.set_title("Scatterplot e Boxplot: Entropia TERNARIA (Domanda Orig.) vs Accuratezza", pad=15)
    ax1.set_ylabel("Entropia Ternaria Normalizzata [0.0 = Sicuro, 1.0 = Indeciso]")
    ax1.set_ylim(-0.05, 1.05)
    ax1.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=2)
    ax1.grid(axis='y', linestyle='--', alpha=0.7, zorder=0)

    pearson_result = stats.pearsonr(vettore_entropia, vettore_correttezza)
    print(f"Coefficiente di correlazione di Pearson: {pearson_result.statistic}")

    plt.show()

else:
    print("⚠️ Dati non trovati. Assicurati di aver eseguito i blocchi precedenti per caricare il CSV nell'oggetto 'res'.")

if 'res' in locals() and res.risultati_per_tabella:

    dati_estratti_ter = []

    for riga in res.risultati_per_tabella:
        # Estraiamo SOLO la domanda originale (indice 0)
        alt_orig = riga["alternative"][0]

        p_t = alt_orig.get("p_true_raw", 0.0)
        p_f = alt_orig.get("p_false_raw", 0.0)
        p_o = alt_orig.get("p_altri_raw", 0.0)

        # Usiamo la vecchia funzione di Shannon base 3 (limite 1.0)
        ent_norm = calcola_entropia_ternaria(p_t, p_f, p_o)

        risp_orig = alt_orig["risposta_pulita"].strip().lower()
        risp_reale = riga["reale"].strip().lower()
        esito = (risp_orig == risp_reale)

        dati_estratti_ter.append({"entropia": ent_norm, "corretto": esito})

    entropie_ter = [d["entropia"] for d in dati_estratti_ter]

    limiti_quartili = np.percentile(entropie_ter, [0, 25, 50, 75, 100])

    etichette_bins = [f"Q{i+1}\n({limiti_quartili[i]:.4f} - {limiti_quartili[i+1]:.4f})" for i in range(4)]

    corrette_per_q = [0] * 4
    totali_per_q = [0] * 4

    for dato in dati_estratti_ter:
        ent = dato["entropia"]

        indice_q = np.digitize(ent, limiti_quartili) - 1
        indice_q = min(max(indice_q, 0), 3)

        totali_per_q[indice_q] += 1
        if dato["corretto"]:
            corrette_per_q[indice_q] += 1

    accuratezze = [(c / t * 100) if t > 0 else 0 for c, t in zip(corrette_per_q, totali_per_q)]

    fig, ax = plt.subplots(figsize=(9, 5), dpi=100)

    barre = ax.bar(etichette_bins, accuratezze, color='#FF9800', alpha=0.8, edgecolor='#E65100', linewidth=1.5)

    for bar, t in zip(barre, totali_per_q):
        altezza = bar.get_height()
        ax.annotate(f'{altezza:.2f}%\n(n={t})',
                    xy=(bar.get_x() + bar.get_width() / 2, altezza),
                    xytext=(0, 3), textcoords="offset points",
                    ha='center', va='bottom', fontweight='bold', fontsize=9)

    ax.set_title("Accuratezza per Quartili di Entropia TERNARIA (Solo Domanda Orig.)", pad=15)
    ax.set_xlabel("Quartili (Q1 = Più Sicuro  ⟶  Q4 = Più Indeciso)")
    ax.set_ylabel("Accuratezza (%)")
    ax.set_ylim(0, 115)
    ax.grid(axis='y', linestyle='--', alpha=0.7)

    plt.show()

else:
    print("⚠️ Dati non trovati. Assicurati di aver eseguito i blocchi precedenti per caricare il CSV nell'oggetto 'res'.")

"""#DISTRIBUZIONI TERNARIE SU DOMANDE MAGGIORANZA

"""

entropie_corrette_avg_ter = []
entropie_errate_avg_ter = []
vettore_correttezza_ter = []  # 0 se corretta, 1 se sbagliata
vettore_entropia_ter = []     # Valore dell'entropia corrispondente

num_bins = 5
limiti_bins = np.linspace(0, 1, num_bins + 1)
etichette_bins = [f"{limiti_bins[i]:.4f} - {limiti_bins[i+1]:.4f}" for i in range(num_bins)]
corrette_per_bin = [0] * num_bins
totali_per_bin = [0] * num_bins

if 'res' in locals() and res.risultati_per_tabella:

    for riga in res.risultati_per_tabella:
        somma_norm_t = 0.0
        somma_norm_f = 0.0
        somma_norm_o = 0.0
        k_valide = 0

        # Estrazione e normalizzazione su 3 classi
        for alt in riga["alternative"]:
            p_t = alt.get("p_true_raw", 0.0)
            p_f = alt.get("p_false_raw", 0.0)
            p_o = alt.get("p_altri_raw", 0.0)

            somma_raw = p_t + p_f + p_o
            if somma_raw > 0:
                somma_norm_t += p_t / somma_raw
                somma_norm_f += p_f / somma_raw
                somma_norm_o += p_o / somma_raw
                k_valide += 1

        if k_valide > 0:
            # Distribuzione media sulle N varianti
            media_t = somma_norm_t / k_valide
            media_f = somma_norm_f / k_valide
            media_o = somma_norm_o / k_valide

            # Entropia della media (Ternaria base 3 -> Max 1.0)
            ent_media = calcola_entropia_ternaria(media_t, media_f, media_o)

            # Trova la risposta di maggioranza tra le 3 opzioni
            if media_t >= media_f and media_t >= media_o:
                risp_predetta = "true"
            elif media_f > media_t and media_f >= media_o:
                risp_predetta = "false"
            else:
                risp_predetta = "altro"

            risp_reale = riga["reale"].strip().lower()
            esito_corretto = (risp_predetta == risp_reale)

            vettore_entropia_ter.append(ent_media)

            if esito_corretto:
                entropie_corrette_avg_ter.append(ent_media)
                vettore_correttezza_ter.append(0)
            else:
                entropie_errate_avg_ter.append(ent_media)
                vettore_correttezza_ter.append(1)

            indice_bin = min(int(ent_media * num_bins), num_bins - 1)
            totali_per_bin[indice_bin] += 1
            if esito_corretto:
                corrette_per_bin[indice_bin] += 1

    fig1, ax1 = plt.subplots(figsize=(8, 6), dpi=100)

    data_to_plot = [entropie_corrette_avg_ter, entropie_errate_avg_ter]

    bp = ax1.boxplot(data_to_plot, positions=[1, 2], widths=0.4, patch_artist=True, showfliers=False, zorder=1)

    box_colors = ['#FFFFFF', '#FFFFFF']
    box_edges = ['#4CAF50', '#F44336']

    for patch, color, edge in zip(bp['boxes'], box_colors, box_edges):
        patch.set_facecolor(color)
        patch.set_edgecolor(edge)
        patch.set_linewidth(1.5)

    for median in bp['medians']:
        median.set(color='black', linewidth=2)

    jitter_c = np.random.normal(1, 0.05, size=len(entropie_corrette_avg_ter))
    jitter_e = np.random.normal(2, 0.05, size=len(entropie_errate_avg_ter))

    ax1.scatter(jitter_c, entropie_corrette_avg_ter, alpha=0.6, color='#4CAF50',
                edgecolors='white', linewidth=0.5, label=f'Esatte ({len(entropie_corrette_avg_ter)})', zorder=2)

    ax1.scatter(jitter_e, entropie_errate_avg_ter, alpha=0.6, color='#F44336',
                edgecolors='white', linewidth=0.5, label=f'Sbagliate ({len(entropie_errate_avg_ter)})', zorder=2)

    ax1.set_xticks([1, 2])
    ax1.set_xticklabels(['Risposte Esatte', 'Risposte Sbagliate'], fontsize=11, fontweight='bold')

    ax1.set_title("Scatterplot e Boxplot: Entropia TERNARIA (Risposta di Maggioranza) vs Accuratezza", pad=15)
    ax1.set_ylabel("Entropia Ternaria Normalizzata [0.0 = Sicuro, 1.0 = Indeciso]")

    ax1.set_ylim(-0.05, 1.05)
    ax1.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=2)
    ax1.grid(axis='y', linestyle='--', alpha=0.7, zorder=0)

    if len(vettore_entropia_ter) > 1:
        pearson_result = stats.pearsonr(vettore_entropia_ter, vettore_correttezza_ter)
        print(f"Coefficiente di correlazione di Pearson: {pearson_result.statistic}")

    plt.show()

else:
    print("⚠️ Dati non trovati. Assicurati di aver eseguito i blocchi precedenti per caricare il CSV nell'oggetto 'res'.")

if 'res' in locals() and res.risultati_per_tabella:
    dati_estratti_avg_ter = []

    for riga in res.risultati_per_tabella:
        somma_norm_t = 0.0
        somma_norm_f = 0.0
        somma_norm_o = 0.0
        k_valide = 0

        # Sommiamo e normalizziamo le probabilità di TUTTE le varianti
        for alt in riga["alternative"]:
            p_t = alt.get("p_true_raw", 0.0)
            p_f = alt.get("p_false_raw", 0.0)
            p_o = alt.get("p_altri_raw", 0.0)

            somma_raw = p_t + p_f + p_o
            if somma_raw > 0:
                somma_norm_t += p_t / somma_raw
                somma_norm_f += p_f / somma_raw
                somma_norm_o += p_o / somma_raw
                k_valide += 1

        if k_valide > 0:
            # Calcolo delle probabilità medie (Ensemble)
            media_t = somma_norm_t / k_valide
            media_f = somma_norm_f / k_valide
            media_o = somma_norm_o / k_valide

            # Entropia della media usando la funzione ternaria in base 3
            ent_media = calcola_entropia_ternaria(media_t, media_f, media_o)

            # Determiniamo la risposta predetta dalla maggioranza
            if media_t >= media_f and media_t >= media_o:
                risp_predetta = "true"
            elif media_f > media_t and media_f >= media_o:
                risp_predetta = "false"
            else:
                risp_predetta = "altro"

            risp_reale = riga["reale"].strip().lower()
            esito_corretto = (risp_predetta == risp_reale)

            dati_estratti_avg_ter.append({"entropia": ent_media, "corretto": esito_corretto})

    entropie_avg_ter = [d["entropia"] for d in dati_estratti_avg_ter]

    limiti_quartili = np.percentile(entropie_avg_ter, [0, 25, 50, 75, 100])

    corrette_per_q = [0] * 4
    totali_per_q = [0] * 4

    for dato in dati_estratti_avg_ter:
        ent = dato["entropia"]

        indice_q = np.digitize(ent, limiti_quartili) - 1
        indice_q = min(max(indice_q, 0), 3)

        totali_per_q[indice_q] += 1
        if dato["corretto"]:
            corrette_per_q[indice_q] += 1

    accuratezze = [(c / t * 100) if t > 0 else 0 for c, t in zip(corrette_per_q, totali_per_q)]

    fig, ax = plt.subplots(figsize=(8, 5), dpi=100)

    etichette_q = [f"Q{i+1}\n({limiti_quartili[i]:.4f} - {limiti_quartili[i+1]:.4f})" for i in range(4)]

    barre = ax.bar(etichette_q, accuratezze, color='#FF9800', alpha=0.85,
                   edgecolor='#E65100', linewidth=1.2, width=0.6)

    for bar, acc, n in zip(barre, accuratezze, totali_per_q):
        ax.annotate(f'{acc:.1f}%\n(n={n})',
                    xy=(bar.get_x() + bar.get_width() / 2, acc),
                    xytext=(0, 5), textcoords="offset points",
                    ha='center', va='bottom', fontweight='bold', fontsize=11)

    ax.set_title("Accuratezza per Quartili di Entropia TERNARIA (Risposta di Maggioranza)", pad=15)
    ax.set_ylabel("Accuratezza (%)")
    ax.set_ylim(0, 115)
    ax.grid(axis='y', linestyle='--', alpha=0.7)
    ax.legend()
    plt.show()

else:
    print("⚠️ Dati non trovati. Assicurati di aver eseguito i blocchi precedenti per caricare il CSV nell'oggetto 'res'.")

"""#DISTRIBUZIONI TERNARIE TUTTE LE DOMANDE

"""

entropie_corrette_all_ter = []
entropie_errate_all_ter = []
vettore_correttezza_all_ter = []  # 0 se corretta, 1 se sbagliata
vettore_entropia_all_ter = []     # Valore dell'entropia corrispondente

if 'res' in locals() and res.risultati_per_tabella:

    for riga in res.risultati_per_tabella:
        # ITERIAMO SU TUTTE LE VARIANTI (Originale + Perturbate)
        for alt in riga["alternative"]:

            # Calcolo Entropia Ternaria per la singola variante
            p_t = alt.get("p_true_raw", 0.0)
            p_f = alt.get("p_false_raw", 0.0)
            p_o = alt.get("p_altri_raw", 0.0)

            # Usiamo la funzione ternaria (assumiamo base 3 normalizzata a 1.0)
            ent = calcola_entropia_ternaria(p_t, p_f, p_o)

            # Verifichiamo se QUESTA SPECIFICA VARIANTE era corretta o sbagliata
            risp_alt = alt.get("risposta_pulita", "").strip().lower()
            risp_reale = riga["reale"].strip().lower()

            vettore_entropia_all_ter.append(ent)

            if risp_alt == risp_reale:
                entropie_corrette_all_ter.append(ent)
                vettore_correttezza_all_ter.append(0)
            else:
                entropie_errate_all_ter.append(ent)
                vettore_correttezza_all_ter.append(1)

    fig, ax = plt.subplots(figsize=(8, 6), dpi=100)

    data_to_plot = [entropie_corrette_all_ter, entropie_errate_all_ter]

    bp = ax.boxplot(data_to_plot, positions=[1, 2], widths=0.4, patch_artist=True, showfliers=False, zorder=1)

    box_colors = ['#FFFFFF', '#FFFFFF']
    box_edges = ['#4CAF50', '#F44336']

    for patch, color, edge in zip(bp['boxes'], box_colors, box_edges):
        patch.set_facecolor(color)
        patch.set_edgecolor(edge)
        patch.set_linewidth(1.5)

    for median in bp['medians']:
        median.set(color='black', linewidth=2)

    jitter_corrette = np.random.normal(1, 0.05, size=len(entropie_corrette_all_ter))
    jitter_errate = np.random.normal(2, 0.05, size=len(entropie_errate_all_ter))

    ax.scatter(jitter_corrette, entropie_corrette_all_ter, alpha=0.5, color='#4CAF50',
               edgecolors='white', linewidth=0.5, label=f'Esatte ({len(entropie_corrette_all_ter)})', zorder=2)

    ax.scatter(jitter_errate, entropie_errate_all_ter, alpha=0.5, color='#F44336',
               edgecolors='white', linewidth=0.5, label=f'Sbagliate ({len(entropie_errate_all_ter)})', zorder=2)

    ax.set_xticks([1, 2])
    ax.set_xticklabels(['Risposte Esatte', 'Risposte Sbagliate'], fontsize=11, fontweight='bold')
    ax.set_title("Distribuzione Entropia TERNARIA (Originale + Varianti) vs Accuratezza", pad=15)
    ax.set_ylabel("Entropia Ternaria Normalizzata [0.0 = Sicuro, 1.0 = Indeciso]")
    ax.set_ylim(-0.05, 1.05)
    ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=2)
    ax.grid(axis='y', linestyle='--', alpha=0.7, zorder=0)

    # Calcolo Pearson
    if len(vettore_entropia_all_ter) > 1:
        pearson_result = stats.pearsonr(vettore_entropia_all_ter, vettore_correttezza_all_ter)
        print(f"Coefficiente di correlazione di Pearson: {pearson_result.statistic}")

    plt.show()

else:
    print("⚠️ Dati non trovati. Assicurati di aver eseguito i blocchi precedenti per caricare il CSV nell'oggetto 'res'.")

if 'res' in locals() and res.risultati_per_tabella:
    dati_estratti_all_ter = []

    for riga in res.risultati_per_tabella:
        # ITERIAMO SU TUTTE LE VARIANTI (Originale + Perturbate)
        for alt in riga["alternative"]:

            # Estrazione probabilità per le 3 classi
            p_t = alt.get("p_true_raw", 0.0)
            p_f = alt.get("p_false_raw", 0.0)
            p_o = alt.get("p_altri_raw", 0.0)

            # Calcolo Entropia Ternaria per la singola variante
            ent = calcola_entropia_ternaria(p_t, p_f, p_o)

            # Verifichiamo se la risposta era corretta
            risp_alt = alt.get("risposta_pulita", "").strip().lower()
            risp_reale = riga["reale"].strip().lower()
            esito = (risp_alt == risp_reale)

            dati_estratti_all_ter.append({"entropia": ent, "corretto": esito})

    entropie_all_ter = [d["entropia"] for d in dati_estratti_all_ter]

    limiti_quartili = np.percentile(entropie_all_ter, [0, 25, 50, 75, 100])

    etichette_bins = [f"Q{i+1}\n({limiti_quartili[i]:.4f} - {limiti_quartili[i+1]:.4f})" for i in range(4)]

    corrette_per_bin = [0] * 4
    totali_per_bin = [0] * 4

    for dato in dati_estratti_all_ter:
        ent = dato["entropia"]

        indice_bin = np.digitize(ent, limiti_quartili) - 1

        indice_bin = min(max(indice_bin, 0), 3)

        totali_per_bin[indice_bin] += 1
        if dato["corretto"]:
            corrette_per_bin[indice_bin] += 1

    accuratezze = []
    for c, t in zip(corrette_per_bin, totali_per_bin):
        if t > 0:
            accuratezze.append((c / t) * 100)
        else:
            accuratezze.append(0.0)

    fig, ax = plt.subplots(figsize=(9, 5), dpi=100)

    barre = ax.bar(etichette_bins, accuratezze, color='#FF9800', alpha=0.8, edgecolor='#E65100', linewidth=1.5)

    for bar, t in zip(barre, totali_per_bin):
        altezza = bar.get_height()
        ax.annotate(f'{altezza:.2f}%\n(n={t})',
                    xy=(bar.get_x() + bar.get_width() / 2, altezza),
                    xytext=(0, 3), textcoords="offset points",
                    ha='center', va='bottom', fontweight='bold', fontsize=9)

    ax.set_title("Accuratezza per Quartili di Entropia TERNARIA (Originale + Tutte le Varianti)", pad=15)
    ax.set_xlabel("Quartili (Q1 = Più Sicuro  ⟶  Q4 = Più Indeciso)")
    ax.set_ylabel("Accuratezza (%)")
    ax.set_ylim(0, 115)
    ax.grid(axis='y', linestyle='--', alpha=0.7)

    plt.show()

else:
    print("⚠️ Dati non trovati. Assicurati di aver eseguito i blocchi precedenti per caricare il CSV nell'oggetto 'res'.")

"""# DELTA ENTROPIA BINARIO E TERNARIA

"""

if 'res' in locals() and res.risultati_per_tabella:
    # Caso Binario
    delta_bin_corrette = []
    delta_bin_errate = []
    vett_delta_bin = []

    # Caso Ternario
    delta_ter_corrette = []
    delta_ter_errate = []
    vett_delta_ter = []

    vett_correttezza = [] # 0 se corretta, 1 se sbagliata

    for riga in res.risultati_per_tabella:
        entropie_bin_domanda = []
        entropie_ter_domanda = []

        # Estraiamo le 5 ripetizioni per questa specifica domanda
        for alt in riga["alternative"]:
            p_t = alt.get("p_true_raw", 0.0)
            p_f = alt.get("p_false_raw", 0.0)
            p_a = alt.get("p_altri_raw", 0.0)

            entropie_bin_domanda.append(calcola_entropia_binaria(p_t, p_f))

            entropie_ter_domanda.append(calcola_entropia_ternaria(p_t, p_f, p_a))

        # Calcolo il DELTA (Max - Min) tra le 5 ripetizioni
        delta_bin = np.max(entropie_bin_domanda) - np.min(entropie_bin_domanda)
        delta_ter = np.max(entropie_ter_domanda) - np.min(entropie_ter_domanda)

        is_corretta = riga.get("corretta", False)

        # Salvataggio nelle liste Binario
        vett_delta_bin.append(delta_bin)
        if is_corretta:
            delta_bin_corrette.append(delta_bin)
        else:
            delta_bin_errate.append(delta_bin)

        # Salvataggio nelle liste Ternario
        vett_delta_ter.append(delta_ter)
        if is_corretta:
            delta_ter_corrette.append(delta_ter)
        else:
            delta_ter_errate.append(delta_ter)

        vett_correttezza.append(0 if is_corretta else 1)


    def plot_delta_entropia(corrette, errate, vettore_delta, vettore_corr, titolo, max_y):
        fig, ax = plt.subplots(figsize=(8, 6), dpi=100)

        data_to_plot = [corrette, errate]

        bp = ax.boxplot(data_to_plot, positions=[1, 2], widths=0.4, patch_artist=True, showfliers=False, zorder=1)

        box_colors = ['#FFFFFF', '#FFFFFF']
        box_edges = ['#4CAF50', '#F44336']

        for patch, color, edge in zip(bp['boxes'], box_colors, box_edges):
            patch.set_facecolor(color)
            patch.set_edgecolor(edge)
            patch.set_linewidth(1.5)

        for median in bp['medians']:
            median.set(color='black', linewidth=2)

        jitter_corrette = np.random.normal(1, 0.05, size=len(corrette))
        jitter_errate = np.random.normal(2, 0.05, size=len(errate))

        ax.scatter(jitter_corrette, corrette, alpha=0.5, color='#4CAF50',
                   edgecolors='white', linewidth=0.5, label=f'Esatte ({len(corrette)})', zorder=2)

        ax.scatter(jitter_errate, errate, alpha=0.5, color='#F44336',
                   edgecolors='white', linewidth=0.5, label=f'Sbagliate ({len(errate)})', zorder=2)

        ax.set_xticks([1, 2])
        ax.set_xticklabels(['Risposte Esatte', 'Risposte Sbagliate'], fontsize=11, fontweight='bold')
        ax.set_title(titolo, pad=15)
        ax.set_ylabel("Delta Entropia (Max - Min) [0 = Stabile, >0 = Instabile]")

        ax.set_ylim(-0.05, 1.05)
        ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=2)
        ax.grid(axis='y', linestyle='--', alpha=0.7, zorder=0)

        if len(vettore_delta) > 1:
            pearson_result = stats.pearsonr(vettore_delta, vettore_corr)
            print(f"Coefficiente di correlazione di Pearson: {pearson_result.statistic}\n")

        plt.show()


    plot_delta_entropia(
        delta_bin_corrette, delta_bin_errate, vett_delta_bin, vett_correttezza,
        "Delta Entropia (Caso BINARIO)", max_y=1.0)

    print("\n")
    plot_delta_entropia(
        delta_ter_corrette, delta_ter_errate, vett_delta_ter, vett_correttezza,
        "Delta Entropia (Caso TERNARIO)", max_y=1.6)

else:
    print("⚠️ Dati non trovati.")